### PR TITLE
Roslyn benchmark updates

### PR DESCRIPTION
**Pull request by 333fred**
Updates the roslyn benchmarks for 3.8.0.

### CODE REVIEW

**Review by mavasani — APPROVED** [review]
Thanks!

**Comment by 333fred** [comment]
@billwert @adamsitnik any advice on addressing these build failures? From what I can see, it looks like master is failing as well?

**Comment by adamsitnik** [comment]
> any advice on addressing these build failures? From what I can see, it looks like master is failing as well?

The CI failures are caused by breaking changes in the SDK: https://github.com/dotnet/performance/pull/1600

I think that you can just ignore them as long as `roslyn release/5.0.1xx` build is green (it is)

**Comment by billwert** [comment]
> I think that you can just ignore them as long as `roslyn release/5.0.1xx` build is green (it is)

Agreed. I'll merge this.

**Pull request merged**
