### PR TITLE
Frozen collection benchmarks

### PR DESCRIPTION
**Pull request by adamsitnik**

### CODE REVIEW

**Comment by cincuranet** [comment]
Related: https://github.com/dotnet/performance/pull/2905

**Comment by adamsitnik** [comment]
`LengthBucketsFrozenDictionary` is expensive to create (I've used version from Nuget.org, without my recent improvements): 5 to even 23 times slower. For small inputs reading can be just on par with regular dictionary, or slightly faster (x2). But for big inputs, it definitely pays off. The question is whether such inputs are not artificial (a LOT of strings of different lengths)?


|                                     Method | Count | ItemsPerBucket |             Mean | Ratio | Allocated | Alloc Ratio |
|------------------------------------------- |------ |--------------- |-----------------:|------:|----------:|------------:|
|                               ToDictionary |    10 |              1 |        105.47 ns |  1.00 |     440 B |        1.00 |
|                         ToFrozenDictionary |    10 |              1 |        141.37 ns |  1.34 |     488 B |        1.11 |
|               ToFrozenDictionary_Optimized |    10 |              1 |        908.73 ns |  8.62 |    3120 B |        7.09 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary |    10 |              5 |        105.48 ns |  1.00 |     440 B |        1.00 |
|                         ToFrozenDictionary |    10 |              5 |        148.05 ns |  1.40 |     488 B |        1.11 |
|               ToFrozenDictionary_Optimized |    10 |              5 |        491.21 ns |  4.66 |    1000 B |        2.27 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary |   100 |              1 |        765.29 ns |  1.00 |    3128 B |        1.00 |
|                         ToFrozenDictionary |   100 |              1 |        777.70 ns |  1.02 |    3176 B |        1.02 |
|               ToFrozenDictionary_Optimized |   100 |              1 |      6,968.69 ns |  9.11 |   30320 B |        9.69 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary |   100 |              5 |        753.61 ns |  1.00 |    3128 B |        1.00 |
|                         ToFrozenDictionary |   100 |              5 |        783.66 ns |  1.04 |    3176 B |        1.02 |
|               ToFrozenDictionary_Optimized |   100 |              5 |      3,710.39 ns |  4.93 |    8768 B |        2.80 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary |  1000 |              1 |      7,247.89 ns |  1.00 |   31016 B |        1.00 |
|                         ToFrozenDictionary |  1000 |              1 |      7,035.65 ns |  0.97 |   31064 B |        1.00 |
|               ToFrozenDictionary_Optimized |  1000 |              1 |     80,330.23 ns | 11.10 |  302344 B |        9.75 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary |  1000 |              5 |      7,354.84 ns |  1.00 |   31016 B |        1.00 |
|                         ToFrozenDictionary |  1000 |              5 |      7,067.00 ns |  0.96 |   31064 B |        1.00 |
|               ToFrozenDictionary_Optimized |  1000 |              5 |     36,393.69 ns |  4.94 |   88040 B |        2.84 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary | 10000 |              1 |    127,058.47 ns |  1.00 |  283017 B |        1.00 |
|                         ToFrozenDictionary | 10000 |              1 |    124,126.66 ns |  0.98 |  283065 B |        1.00 |
|               ToFrozenDictionary_Optimized | 10000 |              1 |  2,973,843.55 ns | 23.41 | 2942195 B |       10.40 |
|                                            |       |                |                  |       |           |             |
|                               ToDictionary | 10000 |              5 |     91,375.70 ns |  1.00 |  283079 B |        1.00 |
|                         ToFrozenDictionary | 10000 |              5 |     89,460.74 ns |  0.98 |  283120 B |        1.00 |
|               ToFrozenDictionary_Optimized | 10000 |              5 |    930,352.03 ns | 10.16 |  871773 B |        3.08 |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary |    10 |              1 |         95.07 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |    10 |              1 |        107.06 ns |  1.13 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |    10 |              1 |         44.37 ns |  0.47 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary |    10 |              5 |         88.06 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |    10 |              5 |         99.00 ns |  1.12 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |    10 |              5 |         91.17 ns |  1.04 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary |   100 |              1 |      1,782.23 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |   100 |              1 |      1,895.35 ns |  1.06 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |   100 |              1 |        432.21 ns |  0.24 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary |   100 |              5 |      1,063.31 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |   100 |              5 |      1,185.04 ns |  1.11 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |   100 |              5 |      1,028.16 ns |  0.97 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary |  1000 |              1 |    113,837.80 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |  1000 |              1 |    115,492.08 ns |  1.02 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |  1000 |              1 |      4,435.48 ns |  0.04 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary |  1000 |              5 |     30,722.59 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |  1000 |              5 |     32,292.28 ns |  1.05 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |  1000 |              5 |      9,273.17 ns |  0.30 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary | 10000 |              1 | 12,592,996.88 ns | 1.000 |         - |          NA |
|          TryGetValue_True_FrozenDictionary | 10000 |              1 | 12,412,889.06 ns | 0.986 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized | 10000 |              1 |     79,795.17 ns | 0.006 |         - |          NA |
|                                            |       |                |                  |       |           |             |
|                TryGetValue_True_Dictionary | 10000 |              5 |  2,707,831.77 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary | 10000 |              5 |  2,711,929.46 ns |  1.00 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized | 10000 |              5 |    141,381.88 ns |  0.05 |         - |          NA |

**Comment by adamsitnik** [comment]
`JustifiedSingleChar`: the creation is 7-10 times more expensive, but reading is 2-3 times faster.

|                                     Method | Count |          Mean | Ratio | Allocated | Alloc Ratio |
|------------------------------------------- |------ |--------------:|------:|----------:|------------:|
|                               ToDictionary |    10 |     108.11 ns |  1.00 |     440 B |        1.00 |
|                         ToFrozenDictionary |    10 |     163.49 ns |  1.50 |     488 B |        1.11 |
|               ToFrozenDictionary_Optimized |    10 |   1,112.17 ns | 10.34 |    2328 B |        5.29 |
|                                            |       |               |       |           |             |
|                               ToDictionary |   100 |     748.31 ns |  1.00 |    3128 B |        1.00 |
|                         ToFrozenDictionary |   100 |     772.91 ns |  1.03 |    3176 B |        1.02 |
|               ToFrozenDictionary_Optimized |   100 |   6,084.09 ns |  8.13 |   14488 B |        4.63 |
|                                            |       |               |       |           |             |
|                               ToDictionary |  1000 |   7,155.94 ns |  1.00 |   31016 B |        1.00 |
|                         ToFrozenDictionary |  1000 |   7,284.59 ns |  1.00 |   31064 B |        1.00 |
|               ToFrozenDictionary_Optimized |  1000 |  56,208.03 ns |  7.85 |  136568 B |        4.40 |
|                                            |       |               |       |           |             |
|                               ToDictionary | 10000 |  93,870.49 ns |  1.00 |  283351 B |        1.00 |
|                         ToFrozenDictionary | 10000 | 100,922.57 ns |  1.06 |  283389 B |        1.00 |
|               ToFrozenDictionary_Optimized | 10000 | 670,828.59 ns |  7.14 | 1278000 B |        4.51 |
|                                            |       |               |       |           |             |
|                TryGetValue_True_Dictionary |    10 |     105.68 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |    10 |     117.96 ns |  1.12 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |    10 |      51.33 ns |  0.49 |         - |          NA |
|                                            |       |               |       |           |             |
|                TryGetValue_True_Dictionary |   100 |   1,163.13 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |   100 |   1,308.13 ns |  1.12 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |   100 |     519.88 ns |  0.45 |         - |          NA |
|                                            |       |               |       |           |             |
|                TryGetValue_True_Dictionary |  1000 |  14,099.56 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |  1000 |  15,595.86 ns |  1.11 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |  1000 |   5,135.91 ns |  0.36 |         - |          NA |
|                                            |       |               |       |           |             |
|                TryGetValue_True_Dictionary | 10000 | 171,112.00 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary | 10000 | 185,635.30 ns |  1.08 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized | 10000 |  51,756.35 ns |  0.30 |         - |          NA |

**Comment by adamsitnik** [comment]
`SubstringFrozenDictionary`: the creation is very expensive, the reads are 10-25% faster

|                                     Method | Count |            Mean | Ratio | Allocated | Alloc Ratio |
|------------------------------------------- |------ |----------------:|------:|----------:|------------:|
|                               ToDictionary |    10 |       107.55 ns |  1.00 |     440 B |        1.00 |
|                         ToFrozenDictionary |    10 |       159.81 ns |  1.51 |     488 B |        1.11 |
|               ToFrozenDictionary_Optimized |    10 |     4,613.64 ns | 42.91 |    3016 B |        6.85 |
|                                            |       |                 |       |           |             |
|                               ToDictionary |   100 |       803.66 ns |  1.00 |    3128 B |        1.00 |
|                         ToFrozenDictionary |   100 |       775.65 ns |  0.95 |    3176 B |        1.02 |
|               ToFrozenDictionary_Optimized |   100 |    41,387.75 ns | 50.72 |   21120 B |        6.75 |
|                                            |       |                 |       |           |             |
|                               ToDictionary |  1000 |     6,957.75 ns |  1.00 |   31016 B |        1.00 |
|                         ToFrozenDictionary |  1000 |     7,116.41 ns |  1.02 |   31064 B |        1.00 |
|               ToFrozenDictionary_Optimized |  1000 |   386,258.70 ns | 55.41 |  177609 B |        5.73 |
|                                            |       |                 |       |           |             |
|                               ToDictionary | 10000 |    93,572.27 ns |  1.00 |  283354 B |        1.00 |
|                         ToFrozenDictionary | 10000 |    92,911.81 ns |  0.99 |  283373 B |        1.00 |
|               ToFrozenDictionary_Optimized | 10000 | 4,390,445.62 ns | 46.84 | 1721788 B |        6.08 |
|                                            |       |                 |       |           |             |
|                TryGetValue_True_Dictionary |    10 |       108.61 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |    10 |       120.62 ns |  1.11 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |    10 |        98.53 ns |  0.91 |         - |          NA |
|                                            |       |                 |       |           |             |
|                TryGetValue_True_Dictionary |   100 |     1,254.71 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |   100 |     1,381.22 ns |  1.10 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |   100 |     1,013.78 ns |  0.80 |         - |          NA |
|                                            |       |                 |       |           |             |
|                TryGetValue_True_Dictionary |  1000 |    13,907.48 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary |  1000 |    15,120.77 ns |  1.09 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized |  1000 |    11,904.36 ns |  0.86 |         - |          NA |
|                                            |       |                 |       |           |             |
|                TryGetValue_True_Dictionary | 10000 |   172,984.84 ns |  1.00 |         - |          NA |
|          TryGetValue_True_FrozenDictionary | 10000 |   185,187.02 ns |  1.07 |         - |          NA |
| TryGetValue_True_FrozenDictionaryOptimized | 10000 |   130,568.22 ns |  0.75 |         - |          NA |

**Comment by adamsitnik** [comment]
@stephentoub ping

**Review by stephentoub — APPROVED** [review]

**Comment by cincuranet** [comment]
Done.

**Comment by adamsitnik** [comment]
@cincuranet  thanks a lot!

**Pull request merged**
