### PR TITLE
Add JsonNode construction benchmarks

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Contributes to https://github.com/dotnet/runtime/issues/107869

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
I think this is a good start, although we will probably want to put the super fast benchmarks (<100ns per iteration) into a loop or something to get their mean time closer to 200-300ns in order to help minimize noisiness. If you have an idea of how to do this while keeping the tests inline with their goal and can make the change, that would be great, otherwise doing this exercise is one of the items we want to do.

**Comment by LoopedBard3** [comment]
@eiriktsarpalis Left a comment and approved the PR, whether you include the change mentioned in the approval, ping me when you are ready for this to be merged and I can merge it.

**Comment by eiriktsarpalis** [comment]
Something like 26e65c2eb6c01d2b76af1f884ec07cfc0e3f62b8?

**Review by LoopedBard3 — APPROVED** [review]

**Comment by LoopedBard3** [comment]
Yes, exactly like that 👍. Thanks! Just to double check, are you good having this merged once the tests run?

**Comment by eiriktsarpalis** [comment]
Yep, go for it!

**Pull request merged**
