### PR TITLE
Fix TimeToFirstService tests to dispose the ServiceProvider correctly

### PR DESCRIPTION
**Pull request by eerhardt**
Contributes to https://github.com/dotnet/runtime/issues/57146

cc @DrewScoggins @maryamariyan @davidfowl 

(I don't have write permissions, so I can't request reviews)

### CODE REVIEW

**Comment by DrewScoggins** [comment]
LGTM

**Review by adamsitnik — CHANGES_REQUESTED** [review]
Changing `[GlobalCleanup]` to `[IterationCleanup]` means "run this cleanup after each benchmark run", the problem is that it also means "run the benchmark once per iteration" and for short-running benchmarks it usually affects the accuracy in a bad way (stopowatch resolution).

Please move the disposal of the scope to the `[Benchmark]` methods and remove the cleanups.

**Comment by eerhardt** [comment]
> Please move the disposal of the scope to the [Benchmark] methods and remove the cleanups.

The intention of the benchmark, AFAICT, is that it wants to measure how long it takes to "get the first service". This doesn't include disposing the ServiceProvider. So I kind of think this suggestion is contradicting the original intention of the test.

>  the problem is that it also means "run the benchmark once per iteration" and for short-running benchmarks it usually affects the accuracy in a bad way (stopowatch resolution).

This sounds like a bug/problem with BenchmarkDotnet. Have we considered fixing the issue there? It also sounds like `IterationCleanup` should never be used. So why do we have it?

**Comment by eerhardt** [comment]
Is the CI currently broken in this repo? I don't see my change causing any of the errors I'm seeing on CI.

**Comment by billwert** [comment]
Yes we're working on it. :( Sorry. This looks good. I'll merge.

**Pull request merged**
