### PR TITLE
Bump BDN version to 0.13.1.1716

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
cc @adamsitnik @DrewScoggins @lewing

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
Unrelated (I think!) test failures on ubuntu/scenarios:
```
[2022/03/11 22:39:07][INFO] Parsing traces/Startup_-_Static_VB_Console_Template_-_FDD_Publish_startup.trace.zip
[2022/03/11 22:39:07][INFO] Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/03/11 22:39:07][INFO]  ---> System.FormatException: Input string was not in a correct format.
[2022/03/11 22:39:07][INFO]    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
[2022/03/11 22:39:07][INFO]    at System.Int32.Parse(String s)
[2022/03/11 22:39:07][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfPropertyBag.GetIntOrNull(String name)
[2022/03/11 22:39:07][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfStruct..ctor(CtfPropertyBag props, CtfField[] fields)
[2022/03/11 22:39:07][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfMetadata.Load(CtfMetadataParser parser)
[2022/03/11 22:39:07][INFO]    at Microsoft.Diagnostics.Tracing.CtfTraceEventSource..ctor(String fileName)
[2022/03/11 22:39:07][INFO]    at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.GetDispatcherFromFileName(String traceFileName, TraceEventDispatcherOptions options)
[2022/03/11 22:39:07][INFO]    at ScenarioMeasurement.TraceSourceManager..ctor(String fileName) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TraceSourceManager.cs:line 34
[2022/03/11 22:39:07][INFO]    at ScenarioMeasurement.TimeToMainParser.Parse(String mergeTraceFile, String processName, IList`1 pids, String commandLine) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TimeToMainParser.cs:line 29
[2022/03/11 22:39:07][INFO]    at ScenarioMeasurement.Startup.Main(String appExe, MetricType metricType, String scenarioName, String traceName, Boolean processWillExit, Int32 iterations, String iterationSetup, String setupArgs, String iterationCleanup, String cleanupArgs, Int32 timeout, Int32 measurementDelay, String appArgs, String logFileName, String workingDir, Boolean warmup, Boolean guiApp, Boolean skipProfileIteration, String reportJsonPath, String traceDirectory, String environmentVariables, String innerLoopCommand, String innerLoopCommandArgs, Boolean runWithoutExit, Int32 hotReloadIters, Boolean skipMeasurementIteration, Boolean parseOnly) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/Startup.cs:line 321
[2022/03/11 22:39:07][INFO]    --- End of inner exception stack trace ---
[2022/03/11 22:39:07][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[2022/03/11 22:39:07][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass5_0.<<ConfigureConsole>b__0>d.MoveNext()
[2022/03/11 22:39:07][INFO] --- End of stack trace from previous location ---
[2022/03/11 22:39:07][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by radical** [comment]
The failures in `sdk_scenarios` seem to be the same too.

**Comment by DrewScoggins** [comment]
Yeah, LGTM.

**Pull request merged**
