### PR TITLE
Remove perf.groovy

### PR DESCRIPTION
**Pull request by adiaaida**
This needs to go in after https://github.com/dotnet/dotnet-ci/pull/1111

### CODE REVIEW

**Comment by adiaaida** [comment]
This change has absolutely no effect on the AzDO jobs... No idea why legs are failing.

**Comment by adamsitnik** [comment]
> This change has absolutely no effect on the AzDO jobs... No idea why legs are failing.

The new JSON API has changed (`JsonWriterState` does not exist anymore )https://github.com/dotnet/corefx/pull/36961

**Comment by adamsitnik** [comment]
Awesome, it has already been fixed in #437

**Pull request merged**
