### PR TITLE
Set MetricsSupport=false for blazor minapp

### PR DESCRIPTION
**Pull request by radical**
Fixes https://github.com/dotnet/performance/issues/3341 .

### CODE REVIEW

**Review by cincuranet — APPROVED** [review]

**Comment by radical** [comment]
@lewing is this property correct? The docs in runtime mention this as the property name, but I'm not sure what it is affecting.

**Review by LoopedBard3 — APPROVED** [review]
LGTM presuming this property does what is expected.

**Comment by radical** [comment]
Don't merge yet. @radekdoulik opened https://github.com/dotnet/runtime/pull/92696 which would supersede this one.

**Comment by radical** [comment]
Closing this as the the property is set to `false` by default now - https://github.com/dotnet/runtime/pull/92696 .

**Pull request closed without merging**
