### PR TITLE
Adds Microsoft.Extensions.Primitives benchmarks to perf repo

### PR DESCRIPTION
**Pull request by maryamariyan**
Contains history of files also.

cc: @adamsitnik

### CODE REVIEW

**Comment by maryamariyan** [comment]
Notes for later:

- Extensions benchmark tests would go here: https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/libraries

- Aside from Primitives, Also need have Hosting, DI, and Logging perf tests to bring over

**Comment by adamsitnik** [comment]
@maryamariyan looks good to me! could you please solve the conflict in `MicroBenchmarks.csproj` file?

**Comment by maryamariyan** [comment]
@adamsitnik the PR is ready

**Comment by maryamariyan** [comment]
closed in favor or https://github.com/dotnet/performance/pull/1362

**Pull request closed without merging**
