### PR TITLE
Bump BDN to 0.13.1.1728, to pick up fixes for wasm/aot runs

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
cc @adamsitnik @DrewScoggins @LoopedBard3 @lewing

**Comment by radical** [comment]
I can't access the logs to see if any of the failures are related to this PR.

**Comment by LoopedBard3** [comment]
Looks like helix is having problems, we will rerun this once it is fixed.
```
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error : AggregateException: Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (Connection timed out (helix.dot.net:443)) (Connection timed out (helix.dot.net:443)) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken) [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Microsoft.DotNet.Helix.Client.Information.QueueInfoAsync(String queueId, Nullable`1 includeQueueDepth, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Information.cs:line 76 [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 161 [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 267 [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 58 [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error : TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout. [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout) [/__w/1/s/eng/performance/helix.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22157.6/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error :    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Bo
```

**Comment by radical** [comment]
Most failures are of the form ([log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-performance-refs-pull-2323-merge-39c4b3a3ec2c42a0b6/Startup%20-%20Static%20F%23%20Console%20Template%20-%20FDD%20Publish/1/console.d623127d.log?sv=2019-07-07&se=2022-04-08T01%3A38%3A04Z&sr=c&sp=rl&sig=DbYO8T2m4AasoBKFjCuViHNm7PtRe3yyxYAsoxTHTFU%3D)):
```
[2022/03/19 01:50:09][INFO] Parsing traces/Startup_-_Static_F#_Console_Template_-_FDD_Publish_startup.trace.zip
[2022/03/19 01:50:09][INFO] Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/03/19 01:50:09][INFO]  ---> System.FormatException: Input string was not in a correct format.
[2022/03/19 01:50:09][INFO]    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
[2022/03/19 01:50:09][INFO]    at System.Int32.Parse(String s)
[2022/03/19 01:50:09][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfPropertyBag.GetIntOrNull(String name)
[2022/03/19 01:50:09][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfStruct..ctor(CtfPropertyBag props, CtfField[] fields)
[2022/03/19 01:50:09][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfMetadata.Load(CtfMetadataParser parser)
[2022/03/19 01:50:09][INFO]    at Microsoft.Diagnostics.Tracing.CtfTraceEventSource..ctor(String fileName)
[2022/03/19 01:50:09][INFO]    at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.GetDispatcherFromFileName(String traceFileName, TraceEventDispatcherOptions options)
[2022/03/19 01:50:09][INFO]    at ScenarioMeasurement.TraceSourceManager..ctor(String fileName) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TraceSourceManager.cs:line 34
[2022/03/19 01:50:09][INFO]    at ScenarioMeasurement.TimeToMainParser.Parse(String mergeTraceFile, String processName, IList`1 pids, String commandLine) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TimeToMainParser.cs:line 29
[2022/03/19 01:50:09][INFO]    at ScenarioMeasurement.Startup.Main(String appExe, MetricType metricType, String scenarioName, String traceName, Boolean processWillExit, Int32 iterations, String iterationSetup, String setupArgs, String iterationCleanup, String cleanupArgs, Int32 timeout, Int32 measurementDelay, String appArgs, String logFileName, String workingDir, Boolean warmup, Boolean guiApp, Boolean skipProfileIteration, String reportJsonPath, String traceDirectory, String environmentVariables, String innerLoopCommand, String innerLoopCommandArgs, Boolean runWithoutExit, Int32 hotReloadIters, Boolean skipMeasurementIteration, Boolean parseOnly) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/Startup.cs:line 321
[2022/03/19 01:50:09][INFO]    --- End of inner exception stack trace ---
[2022/03/19 01:50:09][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[2022/03/19 01:50:09][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass5_0.<<ConfigureConsole>b__0>d.MoveNext()
[2022/03/19 01:50:09][INFO] --- End of stack trace from previous location ---
[2022/03/19 01:50:09][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
[2022/03/19 01:50:09][ERROR] Process exited with status 1
```

**Comment by radical** [comment]
And [one](https://dev.azure.com/dnceng/public/_build/results?buildId=1670589&view=logs&jobId=c5fa6045-d515-5d9a-e5f3-9bc333d1aeb1&j=ae0d4539-7e34-50b3-a747-3517df0a51b6&t=ec6b01e3-85a7-5d87-d3cd-3fe8be12734c):

```
[2022/03/19 01:54:49][INFO] Unhandled exception. System.IO.IOException: Broken pipe
[2022/03/19 01:54:49][INFO]  ---> System.Net.Sockets.SocketException (32): Broken pipe
[2022/03/19 01:54:49][INFO]    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
[2022/03/19 01:54:49][INFO]    --- End of inner exception stack trace ---
[2022/03/19 01:54:49][INFO]    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
[2022/03/19 01:54:49][INFO]    at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer)
[2022/03/19 01:54:49][INFO]    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
[2022/03/19 01:54:49][INFO]    at System.IO.StreamWriter.WriteLine(String value)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver, Int32 launchIndex)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Int32 launchIndex)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, Int32 totalBenchmarkCount, StartedClock& runsChronometer, Int32& benchmarksToRunCount)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
[2022/03/19 01:54:49][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[2022/03/19 01:54:49][INFO]    at MicroBenchmarks.Program.Main(String[] args) in /datadisks/disk1/work/AFF10982/w/A6570943/e/src/benchmarks/micro/Program.cs:line 44
```

`BenchmarkDotNet.Running.BenchmarkRunnerClean` needs to be more robust against exceptions like this.

**Comment by radical** [comment]
The same errors can be seen in https://github.com/dotnet/performance/pull/2320 which doesn't have the bump, so I think all these are unrelated to the PR.

**Comment by AndyAyersMS** [comment]
What needs to happen to unblock this?

**Comment by LoopedBard3** [comment]
Helix was having problems friday when we were trying to do a check run, but it is back up now. I will go ahead and merge since the tests have run and the failures are either occuring in main or are noisy (micro one), and they have been noted above as occuring otherwise.

**Comment by adamsitnik** [comment]
> Unhandled exception. System.IO.IOException: Broken pipe

I've merged a fix for that, will send another BDN update later today https://github.com/dotnet/BenchmarkDotNet/pull/1958

**Pull request merged**
