### PR TITLE
Bump BDN version to pull in MonoAotLLVM Fixes

### PR DESCRIPTION
**Pull request by naricc**
Bump the BDN version number to pull in fixes to MOnoAOTLLVM tool chain

### CODE REVIEW

**Comment by naricc** [comment]
@DrewScoggins

**Review by SamMonoRT — APPROVED** [review]

**Comment by SamMonoRT** [comment]
@DrewScoggins @LoopedBard3 - please can you merge this asap. This is needed for accurate numbers needed for aot-llvm scenarios, possibly some input for the sync next week.

**Comment by DrewScoggins** [comment]
There was a merge conflict, which I just resolved. I will wait until the CI runs have pulled down the package correctly, and then I will merge this.

**Comment by LoopedBard3** [comment]
Looks like the CI passed with only the currently failing sdk_scenarios failing. Merging.

**Pull request merged**
