### PR TITLE
Update ComWrapper.ParallelRCWLookup loop count

### PR DESCRIPTION
**Pull request by LoopedBard3**
Update ComWrapper.ParallelRCWLookup loop count to be 3 mil per iteration, not per ProcessorCount in the iteration. Manual test using this setup resulted in a mean time of ~3s per op and total runtime of ~70s, a time we can manage. 

Mitigates: https://github.com/dotnet/performance/issues/3448 by setting a consistent loop count that will not cause issues on high core count machines. There may still be some investigation to be done on windows vs linux runtimes and Arm vs x64 runtimes.

From my understanding of https://github.com/dotnet/runtime/pull/91120, this seems like it should still catch any potential regressions similar to the previous setup while ensuring high-core machines don't get hit harder than expected. @AaronRobinsonMSFT does my understanding above make sense?

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by mangod9** [comment]
Doesnt still feel like this test is good to measure across OS/platforms. Assuming this normalizes the test somewhat to get it to finish in reasonable time. On 80 core machines its still going to cause more contention than on smaller machines.

**Comment by LoopedBard3** [comment]
I think that this format still works for OS comparisons on the same hardware since the some total work is being done even taking into account the Task overhead. Another option may be to make something like 6 tasks each doing 500,000 calls. Let me know if this seems like a more desirable solution and I can update the PR to match it.

**Comment by mangod9** [comment]
> Another option may be to make something like 6 tasks each doing 500,000 calls. Let me know if this seems like a more desirable solution and I can update the PR to match it.

will defer to @AaronRobinsonMSFT to determine the right intent for this benchmark.

**Comment by LoopedBard3** [comment]
Merging for now to get some form of fix in. We can still iterate on the test if we decide it is necessary.

**Pull request merged**
