### PR TITLE
Remove the dmlib folder

### PR DESCRIPTION
**Pull request by LoopedBard3**
Removing the dmlib folder. Some configuration issues were found, but there is no obvious place that it is used and it seems stale, so we are going to remove it unless a reason to keep it pops up. The dotnet runtime perf pipeline ran as expected without it included so we should be clear to remove it is the perf run goes as expected.

### CODE REVIEW

**Comment by LoopedBard3** [comment]
This will be good to merge once checks have passed (sdk_scenarios may not pass due to an ongoing issue).

**Comment by DrewScoggins** [comment]
@adamsitnik who did the port of this and maybe knows what it is.

**Comment by adamsitnik** [comment]
> @adamsitnik who did the port of this and maybe knows what it is.

To be honest I don't remember what is it and why I've ported it.

It's most probably some old app that we have used to profile a specific issue for one of the Azure teams (the code says it's "Azue Data Movement Library Benchmark")

Anyway deleting it is a good idea. 👍

**Comment by LoopedBard3** [comment]
SDK_Scenario failures are not specific to this change and the net461 failures are due to an issue with dotnet-install, merging.

**Pull request merged**
