### PR TITLE
Fix markdown encoding.

### PR DESCRIPTION
**Pull request by jorive**

### CODE REVIEW

**Comment by jorive** [comment]
@adamsitnik The file encoding was `UTF16 LE`, and now it is `UTF8 with BOM` like the other readme files.

**Comment by MarcoRossignoli** [comment]
I see binary file again...is expected before merge?

**Comment by jorive** [comment]
@MarcoRossignoli This "dummy" commit: https://github.com/dotnet/performance/pull/294/commits/09e9f19ba3694d443053a3173a8d8271e5961587, shows it as text file.

**Comment by MarcoRossignoli** [comment]
Ah...yes you're right...not on "changes"

**Comment by jorive** [comment]
@MarcoRossignoli thanks!

**Comment by adamsitnik** [comment]
@jorive thanks for the fix! #mysterySolved

**Pull request merged**
