### PR TITLE
Add MacOS PR jobs, fixes #279

### LINKED ISSUE #279: Add MacOS PR jobs

### PR DESCRIPTION
**Pull request by adamsitnik**

### CODE REVIEW

**Comment by adamsitnik** [comment]
The macOS jobs have failed, I need #274 to be fixed first to investigate (most probably missing python ;) )

**Comment by jorive** [comment]
@adamsitnik In non-Windows OS you should be able to call the script directly without explicit python3 in front of it. Instead of: `python3.5 ./scripts/benchmarks_ci.py ...`, you could call: `./scripts/benchmarks_ci.py ...`

**Comment by adamsitnik** [comment]
@jorive thanks, but it did not work. I am afraid that python 2 is the default and this is why we need to specify the full name

```log
Executed on dci-macpro-09.local
chmod: /Users/dotnet-bot/dotnetbuild/work/63d199f7-0bac-459a-a7aa-1b1bddaafd46/Work/c9a1a0cc-dbda-4c8d-a39b-4dcd4e1cef02/Exec/*.sh: No such file or directory
+ /Users/dotnet-bot/dotnetbuild/work/63d199f7-0bac-459a-a7aa-1b1bddaafd46/Payload/benchmarks_ci.py --bin-directory ./bin --working-directory . --incremental no --category corefx --architecture x64 -f netcoreapp2.0 '--bdn-arguments=--iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart --stopOnFirstError true' --benchview-submission-name '.NET Performance - private - merge 281' --benchview-machinepool perfsnake --generate-benchview-data --benchview-run-type private
env: python3: No such file or directory
+ _commandExitCode=127
+ exit 127
```

@safern do you know how can I execute Python 3 scripts using the machines from `OSX.1013.Amd64.Open` queue?

**Comment by jorive** [comment]
@adamsitnik The `shebang` **(https://github.com/dotnet/performance/blob/master/scripts/benchmarks_ci.py#L1)** should pick python3 from the user environment.

**Comment by safern** [comment]
> @safern do you know how can I execute Python 3 scripts using the machines from `OSX.1013.Amd64.Open` queue?

I'm not sure what version of python machines have, but I do know they have an environment variable that points to python.exe -- `$HELIX_PYTHONPATH == python.exe`

**Comment by billwert** [comment]
@adamsitnik Closing this one per our conversation earlier.

**Pull request closed without merging**
