### PR TITLE
Small bug fix, styling, and removing unnecessary parameters.

### PR DESCRIPTION
**Pull request by jorive**
- Remove `--buildTimeout 300` from CI
- Fixed runtime error on python script that was introduced as part of Arcade changes, where: the default `bin` folder was not defined on groovy and the given default value was incorrect.
```log
[2019/01/23 20:53:38][INFO] $ pushd "C:\J\w\coreclr_perf_---d8f56ecc\artifacts\bin\bin"
[2019/01/23 20:53:38][INFO] $ popd
Traceback (most recent call last):
  File ".\scripts\benchmarks_ci.py", line 524, in <module>
    __main(sys.argv[1:])
  File ".\scripts\benchmarks_ci.py", line 520, in __main
    __run_benchview_scripts(args, verbose, BENCHMARKS_CSPROJ)
  File ".\scripts\benchmarks_ci.py", line 357, in __run_benchview_scripts
    name=submission_name)
  File "C:\J\w\coreclr_perf_---d8f56ecc\scripts\benchview.py", line 137, in submission_metadata
    RunCommand(cmdline, verbose=self.verbose).run(working_directory)
  File "C:\J\w\coreclr_perf_---d8f56ecc\scripts\performance\common.py", line 171, in run
    with push_dir(working_directory):
  File "C:\Python35\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\J\w\coreclr_perf_---d8f56ecc\scripts\performance\common.py", line 117, in push_dir
    os.chdir(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\J\\w\\coreclr_perf_---d8f56ecc\\artifacts\\bin\\bin'
```
- Fixed `micro_benchmarks.py` script.
- Autoformatted some of the scripts for styling.

### CODE REVIEW

**Comment by adamsitnik** [comment]
@adiaaida the CI failed with following error:

```log
D:\a\1\s\.dotnet\sdk\2.1.403\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:D:\a\1\s\artifacts\log\x64_CoreCLR_netcoreapp3.0\SendToHelix.binlog /clp:Summary /nr:True /p:TreatWarningsAsErrors=true /warnaserror D:\a\1\s\eng\common\helixpublish.proj
  Sent Helix Job 6fc67fd8-4895-47a6-bfae-829f64186209
  Waiting on job completion...
  Results will be available from https://mc.dot.net/#/user/dotnet-performance/pr~2Fdotnet~2Fperformance~2Frefs~2Fpull~2F241~2Fmerge/test~2Fperformance_x64_coreclr_netcoreapp3.0~2F/20190124.7
C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.helix.sdk\1.0.0-beta.18629.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Work item WorkItem on job 6fc67fd8-4895-47a6-bfae-829f64186209 has failed with exit code 1. [D:\a\1\s\eng\common\helixpublish.proj]
  Job 6fc67fd8-4895-47a6-bfae-829f64186209 is completed with 2 finished work items.

Build FAILED.

C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.helix.sdk\1.0.0-beta.18629.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Work item WorkItem on job 6fc67fd8-4895-47a6-bfae-829f64186209 has failed with exit code 1. [D:\a\1\s\eng\common\helixpublish.proj]
    0 Warning(s)
    1 Error(s)
```

is this something that we should be worried about? this PR should not break anything

**Comment by adiaaida** [comment]
Hm, that is very strange. It looks like Helix unzipped the workload payload into one folder, but then set the HELIX_WORKLOAD_PAYLOAD environment variable to a different folder. I don't know what would cause that, but will ask people around here when they get back.

**Comment by adamsitnik** [comment]
@adiaaida thank you!

**Comment by jorive** [comment]
@adamsitnik @adiaaida Should I merge?

```
2019-01-24T22:11:34.9054098Z ##[section]Starting: Send job to Helix (Windows)
2019-01-24T22:11:34.9058970Z ==============================================================================
2019-01-24T22:11:34.9059144Z Task         : PowerShell
2019-01-24T22:11:34.9059304Z Description  : Run a PowerShell script on Windows, macOS, or Linux.
2019-01-24T22:11:34.9059455Z Version      : 2.140.2
2019-01-24T22:11:34.9059592Z Author       : Microsoft Corporation
2019-01-24T22:11:34.9059755Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2019-01-24T22:11:34.9059935Z ==============================================================================
2019-01-24T22:11:36.8275662Z Generating script.
2019-01-24T22:11:37.1720068Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\d2d507ee-adc6-4ff4-aaec-0e43aa19a043.ps1'"
2019-01-24T22:11:39.8442299Z dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.403/dotnet-sdk-2.1.403-win-x64.zip
2019-01-24T22:11:41.6077794Z dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.403/dotnet-sdk-2.1.403-win-x64.zip
2019-01-24T22:11:50.0735215Z dotnet-install: Adding to current process PATH: "D:\a\1\s\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
2019-01-24T22:11:50.0763545Z dotnet-install: Installation finished
2019-01-24T22:11:50.6810072Z D:\a\1\s\.dotnet\sdk\2.1.403\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:D:\a\1\s\artifacts\log\x64_CoreCLR_netcoreapp3.0\SendToHelix.binlog /clp:Summary /nr:True /p:TreatWarningsAsErrors=true /warnaserror D:\a\1\s\eng\common\helixpublish.proj
2019-01-24T22:11:58.3747150Z   Sent Helix Job fcd3840c-9569-4b6b-bb02-a62423f3442a
2019-01-24T22:11:58.3747435Z   Waiting on job completion...
2019-01-24T22:11:59.4128210Z   Results will be available from https://mc.dot.net/#/user/dotnet-performance/pr~2Fdotnet~2Fperformance~2Frefs~2Fpull~2F241~2Fmerge/test~2Fperformance_x64_coreclr_netcoreapp3.0~2F/20190124.10
2019-01-24T22:42:02.4715588Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.helix.sdk\1.0.0-beta.18629.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Work item WorkItem on job fcd3840c-9569-4b6b-bb02-a62423f3442a has failed with exit code 1. [D:\a\1\s\eng\common\helixpublish.proj]
2019-01-24T22:42:02.6828224Z   Job fcd3840c-9569-4b6b-bb02-a62423f3442a is completed with 2 finished work items.
2019-01-24T22:42:02.6940414Z 
2019-01-24T22:42:02.6940715Z Build FAILED.
2019-01-24T22:42:02.6941980Z 
2019-01-24T22:42:02.6942486Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.helix.sdk\1.0.0-beta.18629.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Work item WorkItem on job fcd3840c-9569-4b6b-bb02-a62423f3442a has failed with exit code 1. [D:\a\1\s\eng\common\helixpublish.proj]
2019-01-24T22:42:02.6942969Z     0 Warning(s)
2019-01-24T22:42:02.6943240Z     1 Error(s)
2019-01-24T22:42:02.6944408Z 
2019-01-24T22:42:02.6944995Z Time Elapsed 00:30:11.93
2019-01-24T22:42:02.7416396Z Build failed.
2019-01-24T22:42:02.7548807Z See log: D:\a\1\s\artifacts\log\x64_CoreCLR_netcoreapp3.0\SendToHelix.binlog
2019-01-24T22:42:03.1283912Z ##[error]PowerShell exited with code '1'.
2019-01-24T22:42:03.1769372Z ##[section]Finishing: Send job to Helix (Windows)
```

**Comment by adiaaida** [comment]
Btw, I know these logs aren't helpful. The helpful logs are linked in these logs, so in this case: https://mc.dot.net/#/user/dotnet-performance/pr~2Fdotnet~2Fperformance~2Frefs~2Fpull~2F241~2Fmerge/test~2Fperformance_x64_coreclr_netcoreapp3.0~2F/20190124.10

**Comment by jorive** [comment]
OK, from that link this is what I see:
```cmd
py -3 %HELIX_CORRELATION_PAYLOAD%\benchmarks_ci.py --benchview-submission-name ".NET Performance - CoreClr private - merge 241" --working-directory %HELIX_WORKITEM_PAYLOAD% --bin-directory %HELIX_WORKITEM_PAYLOAD% --incremental no --category CoreCLR --architecture x64 -f netcoreapp3.0 --benchview-machinepool perfsnake --generate-benchview-data --benchview-run-type private  --bdn-arguments="--iterationCount 2"
```
```log
Executed on a00086Q
[2019/01/24 22:41:34][INFO] ----------------------------------------------
[2019/01/24 22:41:34][INFO] Initializing logger 2019-01-24 22:41:34.029878
[2019/01/24 22:41:34][INFO] ----------------------------------------------
[2019/01/24 22:41:34][INFO] Installing tools.
[2019/01/24 22:41:34][INFO] ----------------------
[2019/01/24 22:41:34][INFO] Downloading DotNet Cli
[2019/01/24 22:41:34][INFO] ----------------------
[2019/01/24 22:41:34][INFO] DotNet Install Path: 'C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64'
[2019/01/24 22:41:34][INFO] Downloading https://dot.net/v1/dotnet-install.ps1
[2019/01/24 22:41:34][INFO] $ pushd "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a"
[2019/01/24 22:41:34][INFO] $ powershell.exe -NoProfile -ExecutionPolicy Bypass C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\dotnet-install.ps1 -InstallDir C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64 -Architecture x64 -Channel master
[2019/01/24 22:41:35][INFO] dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview-010157/dotnet-sdk-3.0.100-preview-010157-win-x64.zip
[2019/01/24 22:41:38][INFO] dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview-010157/dotnet-sdk-3.0.100-preview-010157-win-x64.zip
[2019/01/24 22:41:52][INFO] dotnet-install: Adding to current process PATH: "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\". Note: This change will not be visible if PowerShell was run as a child process.
[2019/01/24 22:41:52][INFO] dotnet-install: Installation finished
[2019/01/24 22:41:52][INFO] $ popd
[2019/01/24 22:41:52][INFO] -----------------------------
[2019/01/24 22:41:52][INFO] Downloading BenchView scripts
[2019/01/24 22:41:52][INFO] -----------------------------
[2019/01/24 22:41:53][INFO] http://benchviewtestfeed.azurewebsites.net/api/v2/package/microsoft.benchview.jsonformat/0.1.0-pre029 -> C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\Microsoft.BenchView.JSONFormat
[2019/01/24 22:41:53][INFO] $ dotnet --info
[2019/01/24 22:41:54][INFO] .NET Core SDK (reflecting any global.json):
[2019/01/24 22:41:54][INFO]  Version:   3.0.100-preview-010157
[2019/01/24 22:41:54][INFO]  Commit:    36e48aa03c
[2019/01/24 22:41:54][INFO] 
[2019/01/24 22:41:54][INFO] Runtime Environment:
[2019/01/24 22:41:54][INFO]  OS Name:     Windows
[2019/01/24 22:41:54][INFO]  OS Version:  10.0.17134
[2019/01/24 22:41:54][INFO]  OS Platform: Windows
[2019/01/24 22:41:54][INFO]  RID:         win10-x64
[2019/01/24 22:41:54][INFO]  Base Path:   C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\sdk\3.0.100-preview-010157\
[2019/01/24 22:41:54][INFO] 
[2019/01/24 22:41:54][INFO] Host (useful for support):
[2019/01/24 22:41:54][INFO]   Version: 3.0.0-preview-27324-5
[2019/01/24 22:41:54][INFO]   Commit:  63a01b08e5
[2019/01/24 22:41:54][INFO] 
[2019/01/24 22:41:54][INFO] .NET Core SDKs installed:
[2019/01/24 22:41:54][INFO]   3.0.100-preview-010157 [C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\sdk]
[2019/01/24 22:41:54][INFO] 
[2019/01/24 22:41:54][INFO] .NET Core runtimes installed:
[2019/01/24 22:41:54][INFO]   Microsoft.AspNetCore.App 3.0.0-preview-19074-0431 [C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\shared\Microsoft.AspNetCore.App]
[2019/01/24 22:41:54][INFO]   Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\shared\Microsoft.NETCore.App]
[2019/01/24 22:41:54][INFO]   Microsoft.WindowsDesktop.App 3.0.0-preview-27323-10 [C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\tools\dotnet\x64\shared\Microsoft.WindowsDesktop.App]
[2019/01/24 22:41:54][INFO] 
[2019/01/24 22:41:54][INFO] To install additional .NET Core runtimes or SDKs:
[2019/01/24 22:41:54][INFO]   https://aka.ms/dotnet-download
[2019/01/24 22:41:54][INFO] ---------------------------------------
[2019/01/24 22:41:54][INFO] Removing packages, bin and obj folders.
[2019/01/24 22:41:54][INFO] ---------------------------------------
[2019/01/24 22:41:54][INFO] -------------------------------
[2019/01/24 22:41:54][INFO] Restoring .NET micro benchmarks
[2019/01/24 22:41:54][INFO] -------------------------------
[2019/01/24 22:41:54][INFO] $ pushd "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Work\1b1bf45c-3d9e-46de-869b-8c9d77867a71\Unzip"
[2019/01/24 22:41:54][INFO] $ popd
Traceback (most recent call last):
  File "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload\benchmarks_ci.py", line 541, in <module>
    __main(sys.argv[1:])
  File "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload\benchmarks_ci.py", line 522, in __main
    verbose
  File "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload\micro_benchmarks.py", line 329, in build
    BENCHMARKS_CSPROJ.restore(packages_path=packages, verbose=verbose)
  File "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload\dotnet.py", line 114, in restore
    self.working_directory)
  File "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload\performance\common.py", line 173, in run
    with push_dir(working_directory):
  File "C:\python3.7.0\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload\performance\common.py", line 119, in push_dir
    os.chdir(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\dotnetbuild\\work\\fcd3840c-9569-4b6b-bb02-a62423f3442a\\Work\\1b1bf45c-3d9e-46de-869b-8c9d77867a71\\Unzip'
```

**Comment by jorive** [comment]
Taking a look now.

**Comment by adiaaida** [comment]
I haven't been able to figure that out, TBH, but the HELIX_CORRELATION_PAYLOAD is C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Payload and the HELIX_WORKLOAD_PAYLOAD is C:\dotnetbuild\work\fcd3840c-9569-4b6b-bb02-a62423f3442a\Work\1b1bf45c-3d9e-46de-869b-8c9d77867a71\Unzip

**Comment by jorive** [comment]
These changes fix rolling runs on Jenkins that broke with recent changes to the python scripts. The CI on Azure DevOps has been broken for a while now (https://github.com/dotnet/performance/commits/master) and they are not related to this changes.
I propose merge these changes to keep getting rolling run results, and fix Azure DevOps in a subsequent PR.

**Pull request merged**
