### PR TITLE
Bump verison for BDN changes to wasm-aot tool chain

### PR DESCRIPTION
**Pull request by naricc**
Bump version to take changes to wasm-aot tool chain.

### CODE REVIEW

**Comment by naricc** [comment]
@fanyang-mono

**Review by fanyang-mono — COMMENTED** [review]
wasm-aot tool chain?

**Comment by DrewScoggins** [comment]
I was seeing some nuget failures with the new version, but I can't figure out why. Other workitems in the same job are not seeing the same errors.

**Comment by fanyang-mono** [comment]
> 

Do you have a link to the failure? If so, I could take a look.

**Comment by LoopedBard3** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=1724342&view=logs&j=42a7a126-36bc-5916-05b7-89cb5dc641ec&s=d654deb9-056d-50a2-1717-90c08683d50a if you look under the second attempt for the pipeline tests some tests failed duet to not pulling the correct nuget. The latest attempt seems to have passed all the expected jobs so it may have been a timing/caching issue.

**Comment by DrewScoggins** [comment]
Thanks @LoopedBard3. This LGTM

**Comment by LoopedBard3** [comment]
SDK_Scenarios issue is also occuring on main, merging.

**Review by LoopedBard3 — APPROVED** [review]
LGTM

**Review by DrewScoggins — APPROVED** [review]

**Pull request merged**
