### PR TITLE
Deprecated the old python infrastructure in favor of the new C# Infra

### PR DESCRIPTION
**Pull request by mrsharm**
- Deprecates all python code, documentation and other misc tooling related to the python infrastructure. 
- GCPerfSim and the Environment based scripts are moved out of the python infrastructure.

### CODE REVIEW

**Comment by markples** [comment]
@mrsharm Are there any parts that you think deserve a closer look?

From a quick look,
- Is the C# code (managed-lib[-executable]) fully a utility of the Python code?
- Do the .md files (and associated graphics) have concepts that are still needed when using the C# infrastructure?

**Comment by mrsharm** [comment]
@markples: 

1. Based on our testing so far, we should be 1 to 1 with the python infrastructure. There were some aspects such as the weighted scores that weren't considered to be important to move to the C# infra. 
2. The md files are completely redundant as they were based on the old infra. 

Since you most recently ran the infrastructure, please feel free to start creating issues highlight and suggestions for documentation.

**Review by markples — DISMISSED** [review]
Since anyone using the python infra may end up as this PR, I wanted to point out some of the new documentation locations in the repo: `src\benchmarks\gc\GC.Infrastructure\README.md` has a lot of information, and then `src\benchmarks\gc\GC.Infrastructure\GC.Analysis.API\README.md`, `src\benchmarks\gc\GC.Infrastructure\Notebooks\README.md`, and `src\benchmarks\micro\README.md` have more.

I haven't done a big scan, but there are probably a few more references to the python infra (like "Jupyter" in `GC.Analysis.API\README.md`), but I also don't think this needs to be 100% to merge.

**Comment by Maoni0** [comment]
@cincuranet, the test failures aren't related to the GC changes, could you please take a look? this means I cannot merge it (obviously we'll resolve the conflicts first)

**Comment by cincuranet** [comment]
Yes, unrelated. I'll merge on red after the conflicts are resolved.

**Comment by mrsharm** [comment]
I think I messed something up here by rebasing to the latest changes in order to resolve merge conflicts.

**Pull request closed without merging**
