### PR TITLE
Bump BDN version to include recent bug fixes

### PR DESCRIPTION
**Pull request by adamsitnik**
This version update contains fix for resource leak that was preventing me from running all benchmarks on my Ubuntu machine (https://github.com/dotnet/performance/issues/2738) and full .NET 8 support (https://github.com/dotnet/BenchmarkDotNet/pull/2192).

Since `--resume` support has been now officialy added to BDN itself (https://github.com/dotnet/BenchmarkDotNet/pull/2164), I've removed the previous implementation that was added only to this repo.

@LoopedBard3 In an hour from now [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/45417285) build should get green and publish `0.13.2.2007` to BDN feed. Could you please upload it to our mirror feed?

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
LGTM, assuming general test success

**Comment by LoopedBard3** [comment]
Uploaded the new version to the feed, running another test run to make sure the PR mostly succeeds with the new version.

**Comment by adamsitnik** [comment]
@LoopedBard3 thank you!

**Pull request merged**
