### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Fix typo "threshold"

/cc @adamsitnik

### CODE REVIEW

**Comment by adamsitnik** [comment]
@MarcoRossignoli thank you!

**Comment by jorive** [comment]
@adamsitnik would you know why this file is showing as binary?

**Comment by adamsitnik** [comment]
@jorive I have no idea. I have tried to figure this out once, but spent 15 minutes and just gave up.

**Comment by MarcoRossignoli** [comment]
I look around and seem that when file is encoded as UTF-16 it's recognized as binary.

**Pull request merged**
