### PR TITLE
The current scope already contains a variable of the name jobName/newJob

### PR DESCRIPTION
**Pull request by jorive**

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
This change fixes:
```log
ERROR: startup failed:
12:09:30 perf.groovy: 112: The current scope already contains a variable of the name jobName
12:09:30  @ line 112, column 21.
12:09:30                    def jobName = "coreclr_perf_${os}_${arch}"
12:09:30                        ^
12:09:30 
12:09:30 perf.groovy: 113: The current scope already contains a variable of the name newJob
12:09:30  @ line 113, column 21.
12:09:30                    def newJob = job(InternalUtilities.getFullJobName(project, jobName, isPR)) {
12:09:30                        ^
12:09:30 
12:09:30 2 errors
```

**Comment by adiaaida** [comment]
I'm not sure. @mmitche We recently moved this repo from being private to public. This is the first time we've changed/tested the groovy since. Do you know if the failure we are seeing is related? Do we need to move the performance repo to the dotnet-ci repolist?

**Comment by mmitche** [comment]
Yeah it needs to be moved.

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@mmitche What do I need to remove to disable the old/private repo instance?

**Comment by mmitche** [comment]
@jorive Remove from dotnet-ci-internal.

**Pull request merged**
