### PR TITLE
[release/6.0] Update dependencies.

### PR DESCRIPTION
**Pull request by LoopedBard3**
Updates jupyterlab 1.2.21 -> 3.6.7 and ruamel.yaml 0.16.5 -> 0.16.10.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
Do we have a way to make sure this isn't breaking the GC tests that use these libraries?

**Comment by LoopedBard3** [comment]
> Do we have a way to make sure this isn't breaking the GC tests that use these libraries?
> 
> Other than being sure on that this LGTM.

@mrsharm Is there something we can do to verify this (presuming release/6.0 is still in use)?

**Comment by LoopedBard3** [comment]
Per: https://github.com/dotnet/performance/pull/3916#issuecomment-1942272674 Will merge once there is an approved review.

**Review by DrewScoggins — APPROVED** [review]

**Comment by mrsharm** [comment]
> > Do we have a way to make sure this isn't breaking the GC tests that use these libraries?
> > Other than being sure on that this LGTM.
> 
> @mrsharm Is there something we can do to verify this (presuming release/6.0 is still in use)?

Sorry, missed this - we aren't using the python infra anymore. Feel free to make any changes in older branches (will briefly take a look a the PRs) since this is entirely deprecated in the main branch.

**Pull request merged**
