### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by cincuranet**

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
Thanks

**Comment by cincuranet** [comment]
That was fast @danmoseley. :)

**Review by LoopedBard3 — APPROVED** [review]
LGTM, though this will probably fail as scheduled runs are failing so we will need to manually merge.

**Comment by danmoseley** [comment]
Always trying to encourage contributions!

**Comment by cincuranet** [comment]
@LoopedBard3 True. But it's also not a high risk change. :D

**Pull request merged**
