### PR TITLE
Fixed Test Status Files in GC Benchmarking Infra

### PR DESCRIPTION
**Pull request by ivdiazsa**
Whenever benchmarking tests are run using GC Benchmarking Infra's scenarios, it generates *yaml* test status files, which contain information regarding the scenario run, such as benchmark configuration, coreclr information, etc. One of these fields is the *stdout* produced by *GCPerfSim*. The dumping function previously used has problems when dealing with multiline strings, and writes them with strange backslashes and '\n' characters. After investigation and experiments, no configuration was found to help with this.

To solve this issue, this PR adds a new small system to process test results and write their yaml test status files properly. This does not affect any other yaml writing component within GC infra.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
@Maoni0 PTAL

**Comment by Maoni0** [comment]
it'd be very helpful if you could have some example output for before and after this change. thanks!

**Comment by ivdiazsa** [comment]
Here's a comparison between how the *yaml test status files* looked using the previous dump mechanism, versus how they look with the new one.

**OLD**

```yaml
success: true
trace_file_name: a__only_config__0gb__0.etl
process_id: 14972
seconds_taken: 11.256004
test:
  machine:
    name: DESKTOP-S0L8UMK
  coreclr:
    name: a
    coreclr:
      core_root: C:\Git\OtherStuff\CoreCLR-Builds-Tools\Core_Root_x64
  config:
    name: only_config
    config:
      complus_gcserver: true
      complus_gcconcurrent: false
      complus_gcheapcount: 6
  benchmark:
    name: 0gb
    benchmark:
      arguments:
        tc: 6
        tagb: 100.0
        tlgb: 0.0
        lohar: 0
        sohsi: 0
        lohsi: 0
        pohsi: 0
        sohpi: 0
        lohpi: 0
        pohpi: 0
        sohfi: 0
        lohfi: 0
        pohfi: 0
        allocType: reference
        testKind: time
      min_seconds: 10.0
stdout: "allocating 17,895,697,066 per thread\nRunning 64-bit? True\nPID: 14972\n\
  Running 6 threads.\ntime, ReferenceItem, tlgb 0, tagb 16.666666666045785, totalMins\
  \ 0, buckets:\n    100-204800; surv every 0; pin every 0; weight 12; isPoh True\n\
  \    100-4000; surv every 0; pin every 0; weight 988; isPoh False\nThread 2 stopping\
  \ phase after 17066.666666030884MB\nThread 3 stopping phase after 17066.666666030884MB\n\
  Thread 0 stopping phase after 17066.666666030884MB\nThread 4 stopping phase after\
  \ 17066.666666030884MB\nThread 5 stopping phase after 17066.666666030884MB\nThread\
  \ 1 stopping phase after 17066.666666030884MB\n=== STATS ===\nseconds_taken: 10.9570508\n\
  collection_counts: [4189, 2218, 2217]\nnum_created_with_finalizers: 0\nnum_finalized:\
  \ 0\nfinal_total_memory_bytes: 33979632\nfinal_heap_size_bytes: 171480\nfinal_fragmentation_bytes:\
  \ 464\n"
gcperfsim_result:
  seconds_taken: 10.9570508
  num_created_with_finalizers: 0
  num_finalized: 0
  final_total_memory_bytes: 33979632
  collection_counts:
  - 4189
  - 2218
  - 2217
  final_heap_size_bytes: 171480
  final_fragmentation_bytes: 464
```

**NEW**

```yaml
success: True
trace_file_name: a__only_config__0gb__0.etl
process_id: 8356
seconds_taken: 12.437985
test:
  machine:
    name: DESKTOP-S0L8UMK
  coreclr:
    name: a
    coreclr:
      core_root: C:\Git\OtherStuff\CoreCLR-Builds-Tools\Core_Root_x64
  config:
    name: only_config
    config:
      complus_gcserver: True
      complus_gcconcurrent: False
      complus_gcheapcount: 6
  benchmark:
    name: 0gb
    benchmark:
      arguments:
        tc: 6
        tagb: 100.0
        tlgb: 0.0
        lohar: 0
        sohsi: 0
        lohsi: 0
        pohsi: 0
        sohpi: 0
        lohpi: 0
        pohpi: 0
        sohfi: 0
        lohfi: 0
        pohfi: 0
        allocType: reference
        testKind: time
      min_seconds: 10.0
stdout: "allocating 17,895,697,066 per thread
Running 64-bit? True
PID: 8356
Running 6 threads.
time, ReferenceItem, tlgb 0, tagb 16.666666666045785, totalMins 0, buckets:
    100-204800; surv every 0; pin every 0; weight 12; isPoh True
    100-4000; surv every 0; pin every 0; weight 988; isPoh False
Thread 1 stopping phase after 17066.666666030884MB
Thread 2 stopping phase after 17066.666666030884MB
Thread 3 stopping phase after 17066.666666030884MB
Thread 0 stopping phase after 17066.666666030884MB
Thread 4 stopping phase after 17066.666666030884MB
Thread 5 stopping phase after 17066.666666030884MB
=== STATS ===
seconds_taken: 12.182063
collection_counts: [4130, 2225, 2223]
num_created_with_finalizers: 0
num_finalized: 0
final_total_memory_bytes: 33756808
final_heap_size_bytes: 172072
final_fragmentation_bytes: 440
"
gcperfsim_result:
  seconds_taken: 12.182063
  num_created_with_finalizers: 0
  num_finalized: 0
  final_total_memory_bytes: 33756808
  collection_counts: [4130, 2225, 2223]
  final_heap_size_bytes: 172072
  final_fragmentation_bytes: 440
```

**Comment by Maoni0** [comment]
wonderful! thanks @ivdiazsa. the only nit I have is it'd be more consistent with other parts this file to make stdout look like them, ie, first line starts not on the same line as "stdout:" itself, no quotes and lines are indented with the same # of spaces - it'd look like this (should be 2 space indentation instead of 4 I have here): 

```yaml
stdout: 
    allocating 17,895,697,066 per thread
    Running 64-bit? True
    PID: 8356
    Running 6 threads.
    time, ReferenceItem, tlgb 0, tagb 16.666666666045785, totalMins 0, buckets:
        100-204800; surv every 0; pin every 0; weight 12; isPoh True
        100-4000; surv every 0; pin every 0; weight 988; isPoh False
    Thread 1 stopping phase after 17066.666666030884MB
    Thread 2 stopping phase after 17066.666666030884MB
    Thread 3 stopping phase after 17066.666666030884MB
    Thread 0 stopping phase after 17066.666666030884MB
    Thread 4 stopping phase after 17066.666666030884MB
    Thread 5 stopping phase after 17066.666666030884MB
    === STATS ===
    seconds_taken: 12.182063
    collection_counts: [4130, 2225, 2223]
    num_created_with_finalizers: 0
    num_finalized: 0
    final_total_memory_bytes: 33756808
    final_heap_size_bytes: 172072
    final_fragmentation_bytes: 440
```

**Comment by ivdiazsa** [comment]
Thanks Maoni! I have now added special handling for the *stdout* field. I had to keep the quotes because otherwise, there are problems when parsing this new yaml file, like for example when issuing `py . analyze-single`.

Here's how the output looks now:

```yaml
success: True
trace_file_name: a__only_config__0gb__0.etl
process_id: 16500
seconds_taken: 11.997529
test:
  machine:
    name: DESKTOP-S0L8UMK
  coreclr:
    name: a
    coreclr:
      core_root: C:\Git\OtherStuff\CoreCLR-Builds-Tools\Core_Root_x64
  config:
    name: only_config
    config:
      complus_gcserver: True
      complus_gcconcurrent: False
      complus_gcheapcount: 6
  benchmark:
    name: 0gb
    benchmark:
      arguments:
        tc: 6
        tagb: 100.0
        tlgb: 0.0
        lohar: 0
        sohsi: 0
        lohsi: 0
        pohsi: 0
        sohpi: 0
        lohpi: 0
        pohpi: 0
        sohfi: 0
        lohfi: 0
        pohfi: 0
        allocType: reference
        testKind: time
      min_seconds: 10.0
stdout:
  "allocating 17,895,697,066 per thread
  Running 64-bit? True
  PID: 16500
  Running 6 threads.
  time, ReferenceItem, tlgb 0, tagb 16.666666666045785, totalMins 0, buckets:
      100-204800; surv every 0; pin every 0; weight 12; isPoh True
      100-4000; surv every 0; pin every 0; weight 988; isPoh False
  Thread 0 stopping phase after 17066.666666030884MB
  Thread 5 stopping phase after 17066.666666030884MB
  Thread 3 stopping phase after 17066.666666030884MB
  Thread 1 stopping phase after 17066.666666030884MB
  Thread 2 stopping phase after 17066.666666030884MB
  Thread 4 stopping phase after 17066.666666030884MB
  === STATS ===
  seconds_taken: 11.7776812
  collection_counts: [4172, 2205, 2204]
  num_created_with_finalizers: 0
  num_finalized: 0
  final_total_memory_bytes: 22821720
  final_heap_size_bytes: 172032
  final_fragmentation_bytes: 416"
gcperfsim_result:
  seconds_taken: 11.7776812
  num_created_with_finalizers: 0
  num_finalized: 0
  final_total_memory_bytes: 22821720
  collection_counts: [4172, 2205, 2204]
  final_heap_size_bytes: 172032
  final_fragmentation_bytes: 416
```

**Pull request merged**
