### PR TITLE
Vector128 microbenchmarks

### PR DESCRIPTION
**Pull request by matouskozak**
Vector128 microbenchmarks. Both non-generics and generics versions. 

  
Local testing setup:
```
BenchmarkDotNet=v0.13.2.1940-nightly, OS=ubuntu 20.04
Intel Core i7-8665U CPU 1.90GHz (Coffee Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.100-rc.1.22431.12
  [Host]     : .NET 7.0.0 (7.0.22.42610), X64 RyuJIT AVX2
  Job-ZRCHKB : .NET 8.0.0 (42.42.42.42424), X64 RyuJIT SSE4.2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=MonoAOTLLVM  Toolchain=MonoAOTLLVM
IterationTime=250.0000 ms  MaxIterationCount=20  MinIterationCount=15
WarmupCount=1
```

Time needed to run new microbenchmarks locally using Mono AOT compilation with MiniJIT fallback:

| Microbenchmark         | Num benchmarks | Run time (hh:mm:ss) | Global time (hh:mm:ss) |
| ------------------------ | -------------------: |  ----------------------:| -------------------------:|   
| `Perf_Vector128`          |                          12 |                    00:01:33 |                        00:09:55 |
| `Perf_Vector128Float`  |                          48 |                    00:06:44 |                        00:15:07 |
| `Perf_Vector128Int`      |                          48 |                     00:06:47|                        00:15:23 |
| `Perf_Vector128Of<T>` |                        480 |                              XX |                         01:05:18 |

|  X X `<T>`  |  Run time (hh:mm:ss) |
|------------ | -----------------------:|
|`Byte`          |                     00:05:44|
|`Double`     |                     00:05:29|
|`Int16`        |                      00:05:29|
|`Int32`        |                      00:05:37|
|`Int64`        |                      00:05:33|
|`SByte`       |                      00:05:21|
|`Single`      |                      00:05:25|
|`UInt16`     |                      00:05:29|
|`UInt32`     |                      00:05:34|
|`UInt64`     |                      00:05:42|

### CODE REVIEW

**Review by fanyang-mono — APPROVED** [review]

**Comment by matouskozak** [comment]
Checked the failing CI lanes and they don't seem to be related to my change as they were also failing on main at that time e.g., here https://dev.azure.com/dnceng-public/public/_build/results?buildId=67891&view=logs&j=c031d5b3-1a95-5cd3-3bbd-1614cd88da98&t=da2cf600-eb7e-5b2b-f54c-73752134e5f3.

**Comment by fanyang-mono** [comment]
@tannergooding Could you please review this?

**Comment by tannergooding** [comment]
This also needs review/sign-off from someone like @adamsitnik or @DrewScoggins.

**Comment by sblom** [comment]
This is great, @matouskozak!

I'm a little concerned about the 1 hour 45 minute total run-time for these tests.

Is there a meaningful subset that we can put into regular rotation that would catch most categories of potential perf regressions here using a fraction of that total time? (See [the microbenchmark design guidelines](https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#benchmarks-are-not-unit-tests) for some thoughts on this.)

@tannergooding, do you have any thoughts on ways to subset this? (both the generic type list and also perhaps operators with clustered perf behaviors)

**Comment by tannergooding** [comment]
> @tannergooding, do you have any thoughts on ways to subset this? (both the generic type list and also perhaps operators with clustered perf behaviors)

This is a similar problem as with `Vector<T>` where they are core perf primitives that are critical to track perf on for various runtimes.

We could remove the duplicated sets between the `Perf_Vector128T<T>` and `Perf_Vector128Single`/`Perf_Vector128Int32` tests, but otherwise I think the ideal thing is to push for the parallelization support I've raised before. We could also look at sub setting some behind an "outerloop" perf run to differentiate between "critical" and "important".

**Comment by cincuranet** [comment]
@sblom We're now running micro benchmarks in 5 partitions. Maybe we can add few more to split the work more and use simply more machines.

**Comment by matouskozak** [comment]
> We could remove the duplicated sets between the `Perf_Vector128T<T>` and `Perf_Vector128Single`/`Perf_Vector128Int32` tests, but otherwise I think the ideal thing is to push for the parallelization support I've raised before. We could also look at sub setting some behind an "outerloop" perf run to differentiate between "critical" and "important".

I think we could also try to reduce the set of types tested in `Perf_Vector128Of<T>` (`Perf_Vector128T<T>` before, I renamed it to follow the vector naming). But this will be difficult as many APIs use different code paths depending on the type.

**Comment by matouskozak** [comment]
Additional time-saving can be done by running the non-generic microbenchmark together. I tested it locally, and the global time was 26:54, whereas when run separately, it takes around 40 mins.

**Comment by fanyang-mono** [comment]
@sblom Are you okay to merge this? Or is there a way to parallelize the run of these microbenchmarks?

**Comment by sblom** [comment]
I don't think the "parallelize microbenchmarks" experiment is ready.

If we take [@matouskozak's update](https://github.com/dotnet/performance/pull/2679#issuecomment-1303940354), I guess this is okay if we really are exposed to the risk of any single one of these operations regressing with no sign of the regression on any others.

(Admitting my non-expertise here, I remain very surprised that we don't expect, for example `|` and `&` to be impacted with a correlation of approximately 1.0 in future perf regressions.)

**Comment by kotlarmilos** [comment]
Hey @fanyang-mono is there an impact presented by Vector128 operations?

**Comment by tannergooding** [comment]
> (Admitting my non-expertise here, I remain very surprised that we don't expect, for example | and & to be impacted with a correlation of approximately 1.0 in future perf regressions.)

@sblom, most of these APIs are treated intrinsically by the compiler and generate very specific assembly, often 1-3 instructions. In most hardware, even operations like `&` and `|` are "per type" since there may need to be other functionality, such as `masking`, done to fully support the various SIMD factors that can come into play.

For integers you often get `byte` (`int8`/`uint8`), `word` (`int16`/`uint16`), and `dword` (`int32`/`uint32`) everywhere with `qword` (`int64`/`uint64`) being a mix of "works everywhere" and "64-bit only" behavior. For some APIs, like `add`, the sign doesn't "normally" matter. For other APIs, like `greater than`, it does. The exact semantics of which matters is dependent on the target architecture and what ISAs are supported.

For floating-point, its often a separate co-processor/pipeline and will end up getting `float` and `double` separately.

This means that we have between 6 and 10 different types that have to be validated. Most of these types has a core usage:
* `byte` - UTF-8 string processing
* `word` - UTF-16 string processing (.NET default)
* `dword` - Native Target for most .NET integer handling
* `float` - Graphics Processing, Image Manipulation, Machine Learning

We then also have:
* `qword` - Native indexing and pointer support on 64-bit
* `double` - Similar scenarios as float, also the .NET default for many years

For the integer sizes, `byte`/`word` typically prefer `unsigned` where-as `dword` typically prefers `signed`. But we have a decent mix of both throughout, particularly when it comes to comparisons so we can emit more optimal sequences when the input values are known to fit a given constraint (such as being definitely positive).

**Comment by fanyang-mono** [comment]
> Hey @fanyang-mono is there an impact presented by Vector128 operations?

What kind of impact? I don't quite understand your question.

**Comment by kotlarmilos** [comment]
> > Hey @fanyang-mono is there an impact presented by Vector128 operations?
> 
> What kind of impact? I don't quite understand your question.

Speedup achieved by using vector optimizations, i.e. results with and without the changes

**Comment by fanyang-mono** [comment]
@kotlarmilos There microbenchmarks once being merged will be run on the daily bases against `dotnet/runtime`. We will know when future change causes improvements or regression. @matouskozak also ran them locally previously against the changes he made for Vector128 on AMD64. And these microbnenchmarks did prove the impact of his changes.

**Comment by fanyang-mono** [comment]
@sblom Shall we merge this? It seems that everyone agrees that these microbenchmarks are important to have.

**Comment by sblom** [comment]
> Shall we merge this?

Alright.

**Review by sblom — APPROVED** [review]

**Pull request merged**
