### PR TITLE
Update Windows RS4 x64 micro_net461 Open LTS to windows-latest

### PR DESCRIPTION
**Pull request by Tohron**
PR created in response to https://github.com/dotnet/performance/issues/2137
A test pipeline run for this changed passed: https://dev.azure.com/dnceng/internal/_build/results?buildId=1478678&view=results
Is there anything else that needs done?

### CODE REVIEW

**Review by LoopedBard3 — DISMISSED** [review]
Looks good, especially with the successful run. It would probably be good to update all of these pool instances to windows-latest saving us PR's.

**Comment by Tohron** [comment]
I believe all the windows runs now use windows-2019 while the ubuntu runs use ubuntu-latest.  I've observed successful manual runs: https://dev.azure.com/dnceng/internal/_build/results?buildId=1490986&view=results whereas a test of all the runs made it to sending jobs to helix before failing there due to QueueId issues: https://dev.azure.com/dnceng/internal/_build/results?buildId=1491158&view=logs&j=eb966026-ffac-5e5d-c386-bb16f129c37d&t=93c54018-703f-56cb-c07d-6a66042c3bca
Do people see any issues?

**Comment by DrewScoggins** [comment]
I see that you have made a change to the job.yml template. If you want to make this change you will have to make it in the arcade repo as well, as that file is always updated from what is in the arcade repo. You will also need to test this change against all of the other repo's that use arcade, since every repo that uses AzDO for validation is going to rely on this template.

**Comment by Tohron** [comment]
The new version that leaves job.yml as-is also had a pass for the manual runs: https://dev.azure.com/dnceng/internal/_build/results?buildId=1493037&view=results and had the remain runs reach the Send Job to Helix phase: https://dev.azure.com/dnceng/internal/_build/results?buildId=1493092&view=logs&j=9ab9fbb2-110f-5fa5-64f6-2359c0e92838
Are there any other concerns?

**Pull request merged**
