### PR TITLE
Added support for WSL Terminal and show colors on the Summary Section.

### PR DESCRIPTION
**Pull request by ivdiazsa**
Added support for WSL Terminal on Windows. Also, fixed the issue that was preventing colors from showing in the Summary Section when diffing traces.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
@Maoni0 @VSadov Right now, only large percentage differences (I think it's 20%+) in the Summary stats show color. Would we want to also add color to the detailed tables of `py . diff`?

**Comment by ivdiazsa** [comment]
Adding @cshung as well.

**Comment by VSadov** [comment]
Re: color in `py . diff` - I guess, why not. 
How would it look like?

We probably want a separate PR for that.

**Comment by ivdiazsa** [comment]
> Re: color in py . diff - I guess, why not.
> How would it look like?
> We probably want a separate PR for that.

If you run `py . diff` and compare any two trace files, there are at least two sections in the output:
- Summary of important stats
- Each test's detailed stats

Right now, colors are only shown for bigger deltas in the summary section. We might later work on another PR to show color in the detailed section as well.

**Comment by ivdiazsa** [comment]
@billwert @DrewScoggins This PR is ready to merge.

**Pull request merged**
