### PR TITLE
copy python script logs to a folder that gets uploaded by the CI

### PR DESCRIPTION
**Pull request by adamsitnik**

### CODE REVIEW

**Comment by jorive** [comment]
Do you need to copy? Cannot archive the logs folder itself?

**Comment by adamsitnik** [comment]
This is what gets published: https://github.com/dotnet/performance/blob/master/eng/common/templates/job/job.yml#L174

btw thanks to @safern for explaining me how it works!

**Comment by jorive** [comment]
I'm not an expert on yml files, but shouldn't you be using `$PathtoPublish` as the destination path for both batch and bash?

**Comment by adamsitnik** [comment]
I think that here `PathtoPublish` is a name of the parameter for the task (I am not an expert myself)

**Comment by adamsitnik** [comment]
It's not going to work because it's two different machines: one is scheduling the job (and can upload), another one is running the job and producing the results (can't upload in an easy way)

**Pull request closed without merging**
