### PR TITLE
Add FrozenDictionary to collections tests

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
Is there something I need to do to get the build to use preview nuget packages?  These APIs are in System.Collections.Immutable.dll, which ships downlevel, but it appears to be using officially supported packages and thus can't find the APIs downlevel.

**Comment by cincuranet** [comment]
Where is the preview package? Could the feed be added to this https://github.com/dotnet/performance/blob/main/NuGet.config?

**Comment by stephentoub** [comment]
If nothing else, at this point the .NET 8 Preview 1 package is available on nuget.
https://www.nuget.org/packages/System.Collections.Immutable/8.0.0-preview.1.23110.8

**Comment by cincuranet** [comment]
I'll check why `net462` and `nativeaot7.0` are complaining. Rest is green as grass.

**Comment by cincuranet** [comment]
Hmm, for the `nativeaot7.0` `ilc` takes from it's own `packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.3\framework\System.Collections.Immutable.dll`. Not sure how to force it to use the one from NuGet. Any ideas?

cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
> Not sure how to force it to use the one from NuGet. Any ideas?

I don't know of a way short of hacking MSBuild targets. We track this in https://github.com/dotnet/runtime/issues/67080.

Can this be limited to testing with 8.0 NativeAOT?

**Comment by cincuranet** [comment]
> Can this be limited to testing with 8.0 NativeAOT?

Checking...

**Comment by cincuranet** [comment]
Finally all the stars aligned and it's green (Blazor failure is unrelated). Merging.

**Comment by stephentoub** [comment]
Thank you!!

**Pull request merged**
