### PR TITLE
Add logging time on thread

### PR DESCRIPTION
**Pull request by billwert**

### CODE REVIEW

**Comment by DrewScoggins** [comment]
LGTM. It looks like we were returning before we could ever set the parallelism to one for single file. Is that what the deleted return is about?

**Comment by billwert** [comment]
Yup exacty

**Comment by nattress** [comment]
LGTM. Yep that early return was unintentional. If it's easy to wire up, I'd like to add one of each crossgen scenario to the CI so we can catch these sorts of bugs.

**Review by nattress — APPROVED** [review]

**Pull request merged**
