### PR TITLE
Dump DOTNET_ env vars

### PR DESCRIPTION
**Pull request by danmoseley**

### CODE REVIEW

**Comment by danmoseley** [comment]
The recommended prefix for CLR env variables now is DOTNET_. COMPlus_ is still accepted: we should dump both.

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @danmoseley !

**Comment by adamsitnik** [comment]
@danmoseley I've just fetched latest changes and realized that we are now dumping env vars set by the script itself:

```log
[2022/02/04 17:19:03][INFO] ------------------------------------------
[2022/02/04 17:19:03][INFO] Running .NET micro benchmarks for 'net7.0'
[2022/02/04 17:19:03][INFO] ------------------------------------------
[2022/02/04 17:19:03][INFO] --------------------------------------------------
[2022/02/04 17:19:03][INFO] Dumping COMPlus/DOTNET environment:
[2022/02/04 17:19:03][INFO]   "DOTNET_CLI_TELEMETRY_OPTOUT=1"
[2022/02/04 17:19:03][INFO]   "DOTNET_MULTILEVEL_LOOKUP=0"
[2022/02/04 17:19:03][INFO]   "DOTNET_ROOT=D:\projects\performance\tools\dotnet\x86"
[2022/02/04 17:19:03][INFO] --------------------------------------------------
```

is there any chance that you have the time to fix it?

https://github.com/dotnet/performance/blob/0b84186195f9e8497fcfdbac21d89251eb75ee72/scripts/dotnet.py#L782-L785

**Comment by danmoseley** [comment]
I saw that but figured it was accurate after all. Happy to fix- do you want me to hard code the ones to filter?

**Comment by adamsitnik** [comment]
> do you want me to hard code the ones to filter?

That should be fine

**Pull request merged**
