### PR TITLE
Fix real-world scenarios dead link

### PR DESCRIPTION
**Pull request by alaatm**
./src/benchmarks/real-world/README.md -> ./src/benchmarks/real-world/JitBench/README.md

### CODE REVIEW

**Comment by alaatm** [comment]
Hmmm.. not sure why README.md is binary !

**Comment by danmosemsft** [comment]
I don't know why it's binary either. Maybe try your edit over, then force push to this PR branch? I tried to push an experimental change, but I do'nt have rights to your branch.

**Comment by alaatm** [comment]
I tried again but that didn't work either. It appears to be the original file uses some non-standard encoding. My original edit was directly through GitHub. Now when I look at the diff in vscode it shows like this:

**Comment by jorive** [comment]
@alaatm Thanks for the contribution :) I do not know why the file was binary though it was properly rendered on GitHub.

**Pull request merged**
