### PR TITLE
[WIP] Trying to add Linux correctness CI jobs

### PR DESCRIPTION
**Pull request by adamsitnik**

### CODE REVIEW

**Comment by jorive** [comment]
Are the CI jobs running on VMs? Any plan on running on Mac yet?

**Comment by adamsitnik** [comment]
The PR jobs to this repo test the correctness - run all the benchmarks once on a VM just to make sure the PR does not break the benchmarks.

The dotnet sdk jobs run on perfsnakes.

**Comment by adamsitnik** [comment]
> Any plan on running on Mac yet?

As soon as I figure this out I will run on Mac as well. And on ARM if we have any,

**Comment by adamsitnik** [comment]
@adiaaida I need your help. 

I wanted to enable CI runs on Linux so I:

1. Read the Arcade docs about [Choosing a Machine Pool](https://github.com/dotnet/arcade/blob/master/Documentation/ChoosingAMachinePool.md)
2. Chosen a queue from the [helix list](https://helix.dot.net/api/2018-03-14/info/queues)
3. Changed the `.yml` file do mimic what we have for Windows - a public job for PRs and private for sdk updates

But I have failed.

The errorr that I am getting is `BadRequest`:

```log
 HttpOperationException: Operation returned an invalid status code 'BadRequest' [/__w/1/s/eng/common/helixpublish.proj]
    at Microsoft.DotNet.Helix.Client.Job.NewOperationWithHttpMessagesAsync(JobCreationRequest newJob, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/Generated/Job.cs:line 256 [/__w/1/s/eng/common/helixpublish.proj]
    at Microsoft.DotNet.Helix.Client.JobExtensions.NewOperationAsync(IJob operations, JobCreationRequest newJob, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/Generated/JobExtensions.cs:line 66 [/__w/1/s/eng/common/helixpublish.proj]
    at Microsoft.DotNet.Helix.Client.HelixApi.RetryAsync[T](Func`1 function, Action`1 logRetry, Func`2 isRetryable) [/__w/1/s/eng/common/helixpublish.proj]
    at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 153 [/__w/1/s/eng/common/helixpublish.proj]
    at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore() in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 209 [/__w/1/s/eng/common/helixpublish.proj]
    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 43 [/__w/1/s/eng/common/helixpublish.proj]
  [/__w/1/s/eng/common/helixpublish.proj]
```

@adiaaida could you please take a look at my changes in this PR and see if I am doing something wrong?

**Comment by adiaaida** [comment]
@MattGal @alexperovich For some reason, the public linux leg isn't recognizing that this is an external run, and we are getting a BadRequest. In Windows logs we see:

```
No AccessToken provided, using anonymous access to helix api.
Job is external. Switching to anonymous API.
```

but in the linux leg we only see 

```
No AccessToken provided, using anonymous access to helix api.
```

but not recognition that the job is external, which I think accounts for the BadRequest, but I'm not 100% sure there. Any thoughts?

**Comment by adamsitnik** [comment]
@MattGal @alexperovich could you please take a look at the error that we are getting here? We need to have Linux CI runs to be able to ship this repo

**Comment by adamsitnik** [comment]
Closing as I have implemented it in #270

**Pull request closed without merging**
