### PR TITLE
Fix indenting

### PR DESCRIPTION
**Pull request by DrewScoggins**

### CODE REVIEW

**Comment by LoopedBard3** [comment]
I think mrsharm is already working on getting the pipeline working: https://github.com/dotnet/performance/pull/4489

**Comment by mrsharm** [comment]
Thanks a bunch, @DrewScoggins and @LoopedBard3, just cleaning up the tests a bit -- found some unexpected behavior from the process we are using to run the notebooks. Will fix that but so far the rest of the tasks are green.

**Comment by LoopedBard3** [comment]
@DrewScoggins Is this still needed? I think with the PR from mrsharm, we can close this one.

**Review by e-kharion — APPROVED** [review]

**Pull request closed without merging**
