### PR TITLE
Remove workaround for 8.0 WASM

### PR DESCRIPTION
**Pull request by DrewScoggins**
This should fix https://github.com/dotnet/performance/issues/2824.

### CODE REVIEW

**Comment by radical** [comment]
related - https://github.com/dotnet/performance/pull/2816

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
this will roll up a lot of changes into one commit https://github.com/dotnet/performance/issues/2824 has some examples

**Review by LoopedBard3 — APPROVED** [review]
LGTM

**Comment by radical** [comment]
This isn't complete. It needs the `micro_benchmarks.py` change from https://github.com/dotnet/performance/pull/2816/ too.

**Comment by DrewScoggins** [comment]
Yeah, I had noticed that as well. Should we just close this one and use your PR? I think that seems like the best way forward.

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/performance/pull/2816 .

**Pull request closed without merging**
