### PR TITLE
[WIP] Move over extensions repository performance tests 

### PR DESCRIPTION
**Pull request by maryamariyan**
- [x] Bring over history

### CODE REVIEW

**Comment by maryamariyan** [comment]
@adamsitnik I can't switch to making it a draft PR

**Comment by billwert** [comment]
> @adamsitnik I can't switch to making it a draft PR

You can't switch after the PR is made. I'll add WIP to the title which will block the WIP bot. (We don't automerge anyway here.)

**Comment by billwert** [comment]
Turns out Github rolled out the feature we wanted a [couple days ago](https://twitter.com/github/status/1247981718453334019)! Now this is a draft PR.

**Comment by adamsitnik** [comment]
#1362 got merged and it included all changes from this PR, closing.

**Pull request closed without merging**
