### PR TITLE
Add If statement benchmarks

### PR DESCRIPTION
**Pull request by a74nh**

### CODE REVIEW

**Comment by a74nh** [comment]
Some performance diffs when using csel instructions: https://github.com/dotnet/runtime/pull/67894#issuecomment-1172404955

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by danmoseley** [comment]
@kunalspathak  should we merge then?

**Comment by kunalspathak** [comment]
Sure, I am not sure if `centos 7` failures are known, but otherwise, we can merge it.

**Comment by danmoseley** [comment]
Yes they are known.

**Comment by danmoseley** [comment]
Thanks @a74nh sorry for overlooking this.

**Pull request merged**
