### PR TITLE
BenchviewCommitName was only set on private/PR runs.

### PR DESCRIPTION
**Pull request by jorive**

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
```groovy
// It's unclear if the environment variables below will expand as desired
// Are there groovy variable I should be using instead? ${BranchName} ${sha1}?
rolling = "${benchviewCommitNamePrefix} %GIT_BRANCH% %GIT_COMMIT%"
```
@adiaaida @mmitche

**Comment by adiaaida** [comment]
To be honest, I don't know. Where does this get used? It's something that I'll have to consider in the port to AzureDevOps.

**Comment by jorive** [comment]
We use those variables in CoreClr perf.groovy, but I cannot tell where they come from.

**Comment by adiaaida** [comment]
They are set by Jenkins as parameters to the job

**Pull request merged**
