### PR TITLE
Use Regex.Count in regex perf tests

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @joperezr, @danmoseley

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
hopefully should get a nice twitch in the graph..

**Comment by stephentoub** [comment]
> hopefully should get a nice twitch in the graph..

Yes.  I don't think we graph allocation, but it should drop allocation on many of these tests from "a lot" to "zero".

**Comment by stephentoub** [comment]
@DrewScoggins, please review and merge when you have a moment (I don't have write access).

**Comment by danmoseley** [comment]
@DrewScoggins any reason why we shouldn't give write access to all the folks that have write access to dotnet/runtime?
@terrajobst can help tell us the right way to do this.

**Comment by adamsitnik** [comment]
> any reason why we shouldn't give write access to all the folks that have write access to dotnet/runtime?

When I was porting the benchmarks from coreclr and corefx repos, I've realized that they were more like unit tests rather than benchmarks. Example: focusing on edge cases, having hundreds of test cases etc ([more](https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#mindset)). 

To address these issues I've added few validators that simply produce errors ([example](https://github.com/dotnet/performance/blob/main/src/harness/BenchmarkDotNet.Extensions/TooManyTestCasesValidator.cs)) when things are obviously wrong and published the [Microbenchmark Design Guidelines docs](https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md) to share all of the know-how. 

Together with other members of the .NET Perf Team we restricted the write access only to Perf Team members and Perf Champions so we could ensure that all the benchmarks that we merge follow the best practices.

Are we ready to lift the restrictions? Many of the dotnet/performance contributors contribute great benchmarks and they definitely don't need our reviews anymore, however some still do.

Example: https://github.com/dotnet/performance/pull/1719 got three approvals despite violating multiple rules:

1. the build was red as one of the benchmarks was throwing
2. it was using `[IterationSetup]` (https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#iterationsetup)
3. the namespace was incorrect (https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#benchmarks-are-immutable)
4. it wasn't using any of the parametrization features built into BDN but rather having separate benchmark method per test case

For 2 & 3 we could most probably implement a validator and I am sure that nobody would merge a failing PR, however I am not sure about simple best practices like 4.

I am aware of the fact that the write access is often a bottleneck for the perf repo contributors and in a long term it should definitely change.

Since we have recently invested more in detecting the regressions (@DrewScoggins automation, manual perf runs) perhaps we could book  two days in this release cycle to:
* have a talk about Microbenchmark Design Guidelines
* have every member of the .NET libraries Team look at their areas and implement missing benchmarks (we can detect regressions only for areas that have benchmarks, some have none)
* review the benchmarks and grant the write access to everyone who participated?

@danmoseley @jeffhandley what do you think?

**Comment by adamsitnik** [comment]
> With respect to access -- perhaps near term, we could add a few more people like @stephentoub

👍 

> Seems like we would first need a way to understand where the specific interesting gaps are. We don't want low value tests. Couple ideas: where customers report regressions that we missed; where we have taken changes for performance improvements, which aren't covered. Perhaps we should request that any benchmarks exist before we merge performance improvements.

We already do some of these things and we should definitely always do that. But there are areas with no benchmarks where we introduce non-perf changes and sometimes accidentally regress the performance. Usually we find out about that after new .NET version is released, when the customers are reporting the regression. That is what I would like to avoid.

Perhaps we could use Azure Profiler data and see which components are used frequently and ensure that they are all covered?

**Comment by DrewScoggins** [comment]
I am fully onboard with adding @stephentoub, and want to reiterate what Adam was saying. I think that getting more people who have a really solid understanding of the design guidelines for performance tests, and as a result having write access in this repo is a good thing. I also wonder if we could use that time and effort to look over our existing test assets and see if there are places that we could improve the test quality. Better data in will mean better data out.

All that to say, I have added Stephen to the dotnet-perf group, so he should have write access now.

**Comment by stephentoub** [comment]
Thanks for the write access.  And I'm fully on board with the idea of helping devs to better understand how to write good perf tests, but FWIW, this discussion suggests we hold the tests in dotnet/performance to a higher standard than the official .NET product source living in dotnet/runtime.  That, to me, doesn't make sense, and basically tells folks they're not trusted.

**Comment by danmoseley** [comment]
We could create a PR template with a little comment like

[ ] If you're adding or modifying benchmarks, have you verified the changes comply with https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md ? 

And then if folks make a mistake - we teach/learn.

**Comment by danmoseley** [comment]
created https://github.com/dotnet/performance/pull/2258

**Comment by danmoseley** [comment]
linking https://github.com/dotnet/runtime/pull/64289

**Comment by EgorBo** [comment]
Improvements on arm64: https://github.com/dotnet/perf-autofiling-issues/issues/3572

**Comment by danmoseley** [comment]
@DrewScoggins @adamsitnik  , with the new reminder and link added to the PR template, are you comfortable with giving write access to those in dotnet/runtime that have write access, as a trial?

**Comment by DrewScoggins** [comment]
Yeah, I am fine with that. What group should I add to the permission list to get this done?

**Comment by danmoseley** [comment]
We will have to ask @terrajobst . There is also the question about folks on, eg., the aspnetcore team. But one thing at a time perhaps.

**Comment by adamsitnik** [comment]
> with the new reminder and link added to the PR template, are you comfortable with giving write access to those in dotnet/runtime that have write access, as a trial?

image

Let's give it a try ;)

**Pull request merged**
