### PR TITLE
Updating some packages versions.

### PR DESCRIPTION
**Pull request by jorive**

### CODE REVIEW

**Comment by billwert** [comment]
@adamsitnik has been working on a BDN update for a while in #138 and we've hit some weirdness with it. Any update Adam?

**Comment by jorive** [comment]
ping

**Comment by adamsitnik** [comment]
Updating BenchmarkDotNet to a newer version has a dedicated PR - #511. @billwert I am going to update the status of #511 in #511. 

@jorive in the meantime, could you please revert the BDN version update here? otherwise than that, other updates are ok

**Comment by billwert** [comment]
Sorry I got the wrong number. :)

**Pull request merged**
