### PR TITLE
Update centos7 image to net image

### PR DESCRIPTION
**Pull request by LoopedBard3**
Centos is not being supported in net8 because it doesn't have up to date GLIBCXX files. Initial issue figuring this out: https://github.com/dotnet/sdk/issues/31893, additional information: https://github.com/dotnet/runtime/issues/83428

### CODE REVIEW

**Comment by LoopedBard3** [comment]
@adamsitnik CentOS appears to have been chosen as a part of https://github.com/dotnet/performance/pull/2328. I am wondering if you are aware of any specific reasons CentOS was chosen over other containers, such as the ubuntu one this would change the run to? Thanks!

**Review by cincuranet — APPROVED** [review]
LGTM, although we should probably notify interested parties for possible changes in numbers from the OS change.

**Comment by adamsitnik** [comment]
> I am wondering if you are aware of any specific reasons CentOS was chosen over other containers, such as the ubuntu one this would change the run to? 

TBH I did not remember the reason, but from the list of my commits of shame where I was trying to get it working I can see that it just had all native dependencies in place:

image

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @LoopedBard3 !

**Comment by adamsitnik** [comment]
> although we should probably notify interested parties for possible changes in numbers from the OS change.

afaik this CI leg was used only for verification that all benchmarks can be compiler and executed for NativeAOT.

**Comment by adamsitnik** [comment]
I'll merge it to unblock other PRs

**Pull request merged**
