### PR TITLE
[NO MERGE] check if new version of BDN supports .NET Core 5.0

### PR DESCRIPTION
**Pull request by adamsitnik**
The purpose of this PR is to check if the new version of BDN supports .NET Core 5.0 and everything works as expected.

/cc @adiaaida @billwert

### CODE REVIEW

**Comment by adiaaida** [comment]
Looks like everything checked out. So if you want to change this from a draft to a real PR, looks good to me.

**Comment by billwert** [comment]
@adamsitnik did we figure out the remaining diffs?

**Comment by billwert** [comment]
@adamsitnik I see now that this build probably is the CI job for dotnet/BenchmarkDotNet#1188. I am curious if there's a path where BDN can be more accepting to TFMs it doesn't know about, in line with the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle). While I agree that we should be updating BDN with some frequency, I would very much like to never be broken in this manner again.

**Comment by adiaaida** [comment]
I just want to note that getting an update to BDN that supports netcoreapp5.0 is blocking our ability to run per-commit builds in coreclr and corefx (a fact that I just realized while talking to Jarret). So if we can up the priority on figuring out why we're seeing the weird performance impact in your other PR, and get a stable version of BDN that supports netcoreapp5.0, that would be great!

**Comment by adiaaida** [comment]
Thought: could we conditionalize the package reference for netcoreapp5.0 so that we could get that working without affecting any of the earlier releases until we understand the performance differences we saw? We've already switched to the tigers from the snakes, so there's already a break in our graphs, and this seems like a good time to make that switch.

@billwert @adamsitnik

**Comment by adamsitnik** [comment]
I've updated #511 so I am closing this one

**Pull request closed without merging**
