### PR TITLE
[Net8.0] Update channel_map with net8 and organized 6v7v8 groupings.

### PR DESCRIPTION
**Pull request by LoopedBard3**
Updated the channel_map with net8 channels and cleaned up the groups between net6, net7, and net8. Updating to net8 included setting main channel to point to net8. This is part of work to bring up net8.0 testing.

### CODE REVIEW

**Review by caaavik-msft — APPROVED** [review]

**Comment by LoopedBard3** [comment]
It looks like that for the micro runs, the current failure is related to CborWriter not being found: 
```
[2022/10/18 20:30:21][INFO] $ dotnet build C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=C:\h\w\BA9109CC\p\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1
[2022/10/18 20:30:21][INFO] MSBuild version 17.5.0-preview-22511-01+a440ea9cf for .NET
[2022/10/18 20:30:26][INFO]   Reporting -> C:\h\w\BA9109CC\p\artifacts\bin\Reporting\Release\netstandard2.0\Reporting.dll
[2022/10/18 20:30:28][INFO]   BenchmarkDotNet.Extensions -> C:\h\w\BA9109CC\p\artifacts\bin\BenchmarkDotNet.Extensions\Release\netstandard2.0\BenchmarkDotNet.Extensions.dll
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\CoseKeyHelpers.cs(62,66): error CS0246: The type or namespace name 'CborWriter' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\CoseKeyHelpers.cs(157,95): error CS0246: The type or namespace name 'CborReader' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(37,65): error CS0246: The type or namespace name 'CborConformanceMode' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(46,20): error CS0246: The type or namespace name 'CborConformanceMode' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(37,103): error CS0103: The name 'CborConformanceMode' does not exist in the current context [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborWriter.cs(14,17): error CS0246: The type or namespace name 'CborWriter' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] 
[2022/10/18 20:30:34][INFO] Build FAILED.
[2022/10/18 20:30:34][INFO] 
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\CoseKeyHelpers.cs(62,66): error CS0246: The type or namespace name 'CborWriter' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\CoseKeyHelpers.cs(157,95): error CS0246: The type or namespace name 'CborReader' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(37,65): error CS0246: The type or namespace name 'CborConformanceMode' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(46,20): error CS0246: The type or namespace name 'CborConformanceMode' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(37,103): error CS0103: The name 'CborConformanceMode' does not exist in the current context [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO] C:\h\w\BA9109CC\p\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborWriter.cs(14,17): error CS0246: The type or namespace name 'CborWriter' could not be found (are you missing a using directive or an assembly reference?) [C:\h\w\BA9109CC\p\src\benchmarks\micro\MicroBenchmarks.csproj::TargetFramework=net8.0]
[2022/10/18 20:30:34][INFO]     0 Warning(s)
[2022/10/18 20:30:34][INFO]     6 Error(s)
[2022/10/18 20:30:34][INFO] 
```

**Review by caaavik-msft — APPROVED** [review]

**Comment by LoopedBard3** [comment]
Run before reverting nativeaot back to use version 7.0 mostly succeeded in expected places, mostly having maui build issues and some individual failures in sdk_scenarios, merging. Fixes #2687.

**Pull request merged**
