### PR TITLE
Use 3.0 channel to download and install 3.0

### LINKED ISSUE #757: Enable netcoreapp5.0 for performance testing
The latest dotnet versions coming out of the master branch are netcoreapp5.0. Most of the work to enable it (via csprojs and the like) is done, but we need to enable testing in the lab once Benchmark DotNet accepts netcoreapp5.0. Also, we need to get it working for the ML and Roslyn benchmarks.

### PR DESCRIPTION
**Pull request by adamsitnik**
Today I've been doing some Linux perf analysis and while using the python script to download `netcoreapp3.0` for me I realized that it downloaded 3.1

Git blame led me to https://github.com/dotnet/performance/pull/882 which explains that this change was temporary due to the fact that 3.0 release branch wasn't installing properly.

This PR tries to fix that.

Fixes #757

### CODE REVIEW

**Comment by adamsitnik** [comment]
Hmm the 3.1 Unix build fails with a really strange error:

```log
[2019/10/02 10:01:53][INFO] $ dotnet run --project /home/helixbot/work/2d32ebf7-0015-4d93-a2e5-fcb127631286/Work/256b098b-fc77-4e27-ae2d-3b023256ff1a/Exec/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework netcoreapp3.1 --no-restore --no-build -- --anyCategories coreclr corefx --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart --stopOnFirstError true --partition-count 5 --partition-index 0 --artifacts /home/helixbot/work/2d32ebf7-0015-4d93-a2e5-fcb127631286/Work/256b098b-fc77-4e27-ae2d-3b023256ff1a/Uploads/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/2d32ebf7-0015-4d93-a2e5-fcb127631286/Work/256b098b-fc77-4e27-ae2d-3b023256ff1a/Exec/artifacts/packages --runtimes netcoreapp3.1
[2019/10/02 10:01:54][INFO] System.ComponentModel.Win32Exception (13): Permission denied
[2019/10/02 10:01:54][INFO]    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
[2019/10/02 10:01:54][INFO]    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[2019/10/02 10:01:54][INFO]    at System.Diagnostics.Process.Start()
[2019/10/02 10:01:54][INFO]    at Microsoft.DotNet.Cli.Utils.Command.Execute()
[2019/10/02 10:01:54][INFO]    at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
[2019/10/02 10:01:54][INFO]    at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
[2019/10/02 10:01:54][INFO]    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
[2019/10/02 10:01:54][INFO]    at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

I need to wrap my head around it

**Comment by billwert** [comment]
Is there a 3.1 TFM yet? I looked at doing this exact thing a couple weeks ago (#882) and stopped because of it.

**Comment by billwert** [comment]
Okay I verified there's a 3.1 TFM now. @DrewScoggins how do you think we should handle this since we transitioned the 3.0 release like this? I think we can probably a) put it back to 3.0 and b) stop running it since it's RTMed and 3.1 is its servicing branch. Thoughts?

**Comment by DrewScoggins** [comment]
This makes sense to me. I think that running 3.1 will be the most interesting bit here going forward.

**Comment by adamsitnik** [comment]
I've pushed some changes, I will provide a description within 1h

**Comment by adamsitnik** [comment]
Ok, to summarize the changes proposed in this PR:

* changed the python script to download 3.0 bits from 3.0 channel (3.1 change was temporary)
* added 3.1 to the test matrix for public micro benchmark builds for Windows x64 and Ubuntu x64
* changed ML.NET and Roslyn public builds to run as 3.1 explicitly (they already run for 5.0)
* changed private builds to run as 3.1 explicitly (they already run for 5.0)
* changed private scheduled builds to run as 5.0, so far they were running as 3.0 using 3.1 bits

The most important change is the last one. As far as I know, the bar for pushing things to 3.1 is even higher than 3.0 and we should not expect many changes in 3.1. This is why I believe that the private scheduled builds (the thing that runs every 4h) should run 5.0.

I still need to figure out why only on 3.1 on Linux we get "Permission denied" when using `Process.Start`.

**Comment by billwert** [comment]
Can we leave 3.1 for the scheduled runs? It won't hurt, and while frequency will be potentially low that's the only place we get ARM64 coverage.

Otherwise this seems fine to me, once the Linux issue is understood.

**Comment by adamsitnik** [comment]
> Can we leave 3.1 for the scheduled runs?

You mean to have both 3.1 and 5.0? Sure!

**Comment by billwert** [comment]
Yes exactly. Thanks!

Thanks,
-Bill
________________________________

**Comment by adamsitnik** [comment]
@billwert I did not change anything on our side and now the 3.1 build is green. It looks like somebody has fixed the bug in the meantime ;)

image

**Comment by billwert** [comment]
Merged this because it's blocking something else I want :)

**Pull request merged**
