### PR TITLE
add Ubuntu 1604 ARM64 CI

### LINKED ISSUE #273: Add ARM64 PR jobs

### PR DESCRIPTION
**Pull request by adamsitnik**
Fixes #273

### CODE REVIEW

**Comment by jorive** [comment]
@adamsitnik Are you enabling arm64 perf CI run on container? Are there plans to enable arm32 (provided there is hardware)?

**Comment by adamsitnik** [comment]
@jorive I am adding what is available to make sure none of the PRs breaks us. I was able to find ARM64 but no ARM32 Helix queues.

https://github.com/dotnet/coreclr/blob/fc70d035c7a633a63bc783303df01e50ff8c755f/eng/platform-matrix.yml#L22-L26

@billwert is there any progress when it comes to buying ARM32/64 hardware for our perf runs?

**Comment by adamsitnik** [comment]
Btw I enabled only netcoreapp3.0 runs for ARM64 because this is the only .NET Core which supports ARM64:

https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md
https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md
https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md
https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md

**Comment by jorive** [comment]
Does this leg run on container or actual hardware? Not that it matters from CI point of view (check that changes do not break the repo), but I'm just curious :)

**Comment by adamsitnik** [comment]
@jorive I  think that on a container

obraz

<details>

```log
#[section]Starting: Initialize containers
##[command]/usr/bin/docker version --format '{{.Server.Version}}'
'18.09.1'
Docker daemon version: '18.09.1'
##[command]/usr/bin/docker version --format '{{.Client.Version}}'
'18.09.1'
Docker client version: '18.09.1'
##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=4a0b77"
##[command]/usr/bin/docker network prune --force --filter "label=4a0b77"
##[command]/usr/bin/docker network create --label 4a0b77 vsts_network_25d7af92a60e448ca8b1999a2692fed6
adcd38d9b4918efe43202f306698ea45e0a7f35db2283017ad9b97d04be1d839
##[command]/usr/bin/docker pull microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921
ubuntu-16.04-cross-arm64-a3ae44b-20180315221921: Pulling from microsoft/dotnet-buildtools-prereqs
22dc81ace0ea: Pulling fs layer
1a8b3c87dba3: Pulling fs layer
91390a1c435a: Pulling fs layer
07844b14977e: Pulling fs layer
b78396653dae: Pulling fs layer
8ad4b9bf5612: Pulling fs layer
7a3427348b36: Pulling fs layer
bee3d2856952: Pulling fs layer
9ee871cbb1ab: Pulling fs layer
3090b2bc4dc0: Pulling fs layer
85ed084f0716: Pulling fs layer
b78396653dae: Waiting
8ad4b9bf5612: Waiting
7a3427348b36: Waiting
bee3d2856952: Waiting
9ee871cbb1ab: Waiting
07844b14977e: Waiting
85ed084f0716: Waiting
3090b2bc4dc0: Waiting
1a8b3c87dba3: Verifying Checksum
1a8b3c87dba3: Download complete
91390a1c435a: Verifying Checksum
91390a1c435a: Download complete
07844b14977e: Verifying Checksum
07844b14977e: Download complete
b78396653dae: Verifying Checksum
b78396653dae: Download complete
22dc81ace0ea: Verifying Checksum
22dc81ace0ea: Download complete
7a3427348b36: Verifying Checksum
7a3427348b36: Download complete
8ad4b9bf5612: Verifying Checksum
8ad4b9bf5612: Download complete
bee3d2856952: Verifying Checksum
bee3d2856952: Download complete
3090b2bc4dc0: Verifying Checksum
3090b2bc4dc0: Download complete
9ee871cbb1ab: Verifying Checksum
9ee871cbb1ab: Download complete
85ed084f0716: Verifying Checksum
85ed084f0716: Download complete
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
8ad4b9bf5612: Pull complete
7a3427348b36: Pull complete
bee3d2856952: Pull complete
9ee871cbb1ab: Pull complete
3090b2bc4dc0: Pull complete
85ed084f0716: Pull complete
Digest: sha256:44e957590688f8b850a144794512b281d0486fe368bd13a7fc0770ef3aa16e00
Status: Downloaded newer image for microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921
##[command]/usr/bin/docker inspect --format="{{index .Config.Labels \"com.azure.dev.pipelines.agent.handler.node.path\"}}" microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921
##[command]/usr/bin/docker create --name ubuntu_1604_arm64_cross_container_microsoftdotnetbuildtoolsprereqsubuntu1604crossarm64a3ae44b20180315221921_bae85b --label 4a0b77 --network vsts_network_25d7af92a60e448ca8b1999a2692fed6  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/home/vsts/agents/2.146.0/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f
##[command]/usr/bin/docker start c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f
c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f
##[command]/usr/bin/docker ps --all --filter id=c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f Up Less than a second
##[command]/usr/bin/docker exec  c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f sh -c "command -v bash"
/bin/bash
##[command]whoami 
vsts
##[command]id -u vsts
1001
Try create an user with UID '1001' inside the container.
##[command]/usr/bin/docker exec  c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
##[command]/usr/bin/docker exec  c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f useradd -m -u 1001 vsts_azpcontainer
Grant user 'vsts_azpcontainer' SUDO privilege and allow it run any command without authentication.
##[command]/usr/bin/docker exec  c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f groupadd azure_pipelines_sudo
##[command]/usr/bin/docker exec  c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f usermod -a -G azure_pipelines_sudo vsts_azpcontainer
##[command]/usr/bin/docker exec  c923ecd1b9adebefb1feefff6648de76d1d63dfe2c21120ca8b1c5874d85574f su -c "echo '%azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"
##[section]Finishing: Initialize containers
```
</details>

**Comment by billwert** [comment]
> @billwert is there any progress when it comes to buying ARM32/64 hardware for our perf runs?

Still working on it.

**Pull request merged**
