### PR TITLE
don't trigger the CI if only a doc file was changed

### PR DESCRIPTION
**Pull request by adamsitnik**

### CODE REVIEW

**Comment by adamsitnik** [comment]
@adiaaida @billwert as we talked last week, we should not trigger the CI if only a doc file was changed

based on https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#paths

@adiaaida could you please take a look?

**Comment by billwert** [comment]
@adamsitnik @adiaaida does this work? I was surprised to see CI running on my other PR, and even on this PR it seems to have done the whole thing (since it ran 22 checks.) Shouldn't this PR have not had those checks run if this had the desired effect?

**Comment by billwert** [comment]
sorry I guess this one should but #392 seems like it should not?

**Comment by adiaaida** [comment]
I wonder if the **/*.md syntax doesn't work quite how we expect it to.

**Comment by billwert** [comment]
seems we're not the only ones. MicrosoftDocs/vsts-docs#2363. looking at the doc it says the wildcard has to be at the end. so docs/* is fine. @adiaaida do you know where AzDo feature requests get tracked? It'd be nice if this worked.. In the mean time I'll change the paths to be docs/* and all the relative paths to the .md files in the repo.

**Comment by adiaaida** [comment]
@chcosta Who should we contact for AzDO feature requests?

**Comment by adamsitnik** [comment]
> looking at the doc it says the wildcard has to be at the end

it explains why it worked for https://github.com/dotnet/performance/pull/364 but did not work for this PR. It would be great if AzDO could fix it

**Comment by chcosta** [comment]
Please file an issue in https://dnceng.visualstudio.com/internal/_workitems/recentlyupdated/ (set "internal/VSTS" as the Area) and I'll bring this up with Azure DevOps.

**Comment by billwert** [comment]
done thanks @chcosta

**Pull request merged**
