### PR TITLE
SOD formatting

### PR DESCRIPTION
**Pull request by cincuranet**

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
LGTM

**Comment by DrewScoggins** [comment]
Sorry, I was slow here, but our typical code convention is to use `string` for declaring variables, and to use `String` for all of the static functions and properties.

**Comment by cincuranet** [comment]
Do you want me to revert the string part?

**Comment by DrewScoggins** [comment]
Yeah, sorry I forgot to add that part in. I just want to make sure that we keep consistent style across our code.

**Comment by cincuranet** [comment]
#2875 corrects this. I think `.editorconfig` is (over)due. Because the `string` and `String` usage is inconsistent across the codebase.

**Pull request merged**
