### PR TITLE
[wasm] Don't strip native symbols

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
Looks good to me.

**Comment by radical** [comment]
@LoopedBard3 are the failures known?

**Comment by pavelsavara** [comment]
Why we are doing this ? Could it make size bigger and start slower ?

**Comment by LoopedBard3** [comment]
> @LoopedBard3 are the failures known?

The sdk_scenarios failures are, rerunning for the regular scenarios as that seemed to be a transient file access error.

**Comment by radical** [comment]
> Why we are doing this ?

Native traces don't have symbols for failures in microbenchmarks currently, in AOT for example.

>  Could it make size bigger and start slower ?

not sure by how much.

**Comment by LoopedBard3** [comment]
@radical do you have perms to merge? If not, do you want this merged? I can merge it.

**Comment by radical** [comment]
I have the permissions, but waiting for a review from others as this could affect the results.

**Comment by kg** [comment]
Looks OK to me

**Comment by radical** [comment]
ah, I can't merge on red!

**Comment by radical** [comment]
> ah, I can't merge on red!

@LoopedBard3 could you please help with this? 😊

**Pull request merged**
