### PR TITLE
netcoreapp5.0 => net5.0

### LINKED ISSUE #1426: benchmarks_ci.py still requires "netcoreapp5.0"
benchmarks_ci.py still requires "netcoreapp5.0". I am not sure whether "dotnet build" will continue to recognize that indefinitely: it should use "net50" now.

```
C:\git>py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.1 netcore50 --filter "System.Tests.Perf_Int64*"
usage: benchmarks_ci.py [-h] [--architecture {x64,x86,arm,arm64}]
                        [--dotnet-versions DOTNET_VERSIONS [DOTNET_VERSIONS ...]]
                        [--dotnet-compilation-mode {Default,Tiered,NoTiering,FullyJittedNoTiering,MinOpt}]
                        [-f {netcoreapp3.1,netcoreapp2.1,net461,netcoreapp5.0,netcoreapp3.0} [{netcoreapp3.1,netcoreapp2.1,net461,netcoreapp5.0,netcoreapp3.0} ...]]
                        [--incremental {yes,no}] [--enable-hardware-counters]
                        [--filter FILTER [FILTER ...]]
                        [--corerun CORERUN [CORERUN ...]] [--cli CLI]
                        [--bdn-arguments BDN_ARGUMENTS]
                        [--bdn-artifacts BDN_ARTIFACTS] [--csproj CSPROJFILE]
                        [--bin-directory BIN_DIRECTORY]
                        [--cli-source-info {init-tools,repo,cli,args}]
                        [--cli-branch CLI_BRANCH]
                        [--cli-commit-sha CLI_COMMIT_SHA]
                        [--cli-repository CLI_REPOSITORY]
                        [--cli-source-timestamp CLI_SOURCE_TIMESTAMP]
                        [--upload-to-perflab-container] [-q] [--build-only]
                        [--run-only]
benchmarks_ci.py: error: argument -f/--frameworks: invalid choice: 'netcore50' (choose from 'netcoreapp3.1', 'netcoreapp2.1', 'net461', 'netcoreapp5.0', 'netcoreapp3.0')

C:\git>py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.1 netcoreapp5.0 --filter "System.Tests.Perf_Int64*"
...
[2020/08/02 12:54:24][INFO] $ dotnet build C:\git\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework netcoreapp5.0 --no-restore /p:NuGetPackageRoot=C:\git\performance\artifacts\packages
```

### PR DESCRIPTION
**Pull request by adamsitnik**
Fixes #1426

Today @sebastienros has hit an issue when he tried to use crank to run the micro benchmarks

```log
 Determining projects to restore...
  Restored C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\harness\BenchmarkDotNet.Extensions\BenchmarkDotNet.Extensions.csproj (in 434 ms).
  Restored C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\tools\Reporting\Reporting\Reporting.csproj (in 434 ms).
  Restored C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj (in 457 ms).
  Reporting -> C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\artifacts\bin\Reporting\Release\netstandard2.0\Reporting.dll
  BenchmarkDotNet.Extensions -> C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\artifacts\bin\BenchmarkDotNet.Extensions\Release\netstandard2.0\BenchmarkDotNet.Extensions.dll
C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(37,65): error CS0246: The type or namespace name 'CborConformanceMode' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\libraries\System.Formats.Cbor\CoseKeyHelpers.cs(62,66): error CS0246: The type or namespace name 'CborWriter' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(46,20): error CS0246: The type or namespace name 'CborConformanceMode' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\libraries\System.Formats.Cbor\CoseKeyHelpers.cs(157,95): error CS0246: The type or namespace name 'CborReader' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborWriter.cs(14,17): error CS0246: The type or namespace name 'CborWriter' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\libraries\System.Formats.Cbor\Perf.CborReader.cs(37,103): error CS0103: The name 'CborConformanceMode' does not exist in the current context [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-7308\c1hsasy5.32o\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
```

This happened because one of our magical MSBuild conditions uses "netcoreapp5.0":

https://github.com/dotnet/performance/blob/e8a8fc62be32783d62fabffb56d14874d92a87cc/src/benchmarks/micro/MicroBenchmarks.csproj#L35

I could add another condition to it, but I think that renaming `netcoreapp5.0` to `net5.0` is a cleaner solution.

### CODE REVIEW

**Comment by adamsitnik** [comment]
@sebastienros could you try to run the benchmarks against my branch (https://github.com/adamsitnik/performance/tree/net5.0) and see if it works now? or at least you get a different error? as soon as I have confirmation that it helps, I am going to mark it as ready for review and ask the repo owners for a review

**Review by sebastienros — APPROVED** [review]

**Comment by adamsitnik** [comment]
@billwert please take a look

**Comment by adamsitnik** [comment]
windows RS5 x64 micro master failed because of https://github.com/dotnet/runtime/issues/47856

**Comment by sebastienros** [comment]
It's working with your branch.

Examples:

```
BenchmarkDotNet=v0.12.1.1466-nightly, OS=Windows 10.0.17763.107 (1809/October2018Update/Redstone5)
Intel Xeon CPU E5-1650 v3 3.50GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=        2.0.3 [C:\Program Files\dotnet\sdk]
  [Host] : .NET Core 3.1.12 (CoreCLR 4.700.21.6504, CoreFX 4.700.21.6905), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable  Toolchain=InProcessEmitToolchain
IterationTime=250.0000 ms  MaxIterationCount=20  MinIterationCount=15
WarmupCount=1

                   Method |     Mean |   Error |  StdDev |   Median |      Min |      Max |      Gen 0 | Gen 1 | Gen 2 |     Allocated |
------------------------- |---------:|--------:|--------:|---------:|---------:|---------:|-----------:|------:|------:|--------------:|
        Where00LinqQueryX | 577.5 ms | 2.12 ms | 1.88 ms | 577.1 ms | 575.1 ms | 581.0 ms |  9000.0000 |     - |     - |  72,000,000 B |
       Where00LinqMethodX | 652.0 ms | 0.70 ms | 0.66 ms | 652.2 ms | 651.1 ms | 653.2 ms |  9000.0000 |     - |     - |  72,000,272 B |
              Where00ForX | 437.8 ms | 0.22 ms | 0.20 ms | 437.7 ms | 437.4 ms | 438.1 ms | 22000.0000 |     - |     - | 176,000,000 B |
        Where01LinqQueryX | 333.6 ms | 0.17 ms | 0.16 ms | 333.7 ms | 333.3 ms | 333.9 ms |  2000.0000 |     - |     - |  18,000,000 B |
       Where01LinqMethodX | 334.1 ms | 0.19 ms | 0.17 ms | 334.1 ms | 333.8 ms | 334.5 ms |  2000.0000 |     - |     - |  18,000,000 B |
 Where01LinqMethodNestedX | 371.4 ms | 0.32 ms | 0.30 ms | 371.4 ms | 370.9 ms | 371.9 ms |  7000.0000 |     - |     - |  60,000,000 B |
              Where01ForX | 299.4 ms | 0.23 ms | 0.20 ms | 299.4 ms | 299.1 ms | 299.8 ms |  2000.0000 |     - |     - |  22,000,000 B |
       Count00LinqMethodX | 848.1 ms | 1.31 ms | 1.03 ms | 847.9 ms | 847.3 ms | 851.2 ms |  5000.0000 |     - |     - |  40,000,040 B |
              Count00ForX | 378.6 ms | 0.32 ms | 0.30 ms | 378.6 ms | 378.0 ms | 379.1 ms |          - |     - |     - |             - |
        Order00LinqQueryX | 102.7 ms | 0.21 ms | 0.20 ms | 102.7 ms | 102.5 ms | 103.0 ms |  7000.0000 |     - |     - |  58,600,000 B |
       Order00LinqMethodX | 103.4 ms | 0.25 ms | 0.23 ms | 103.4 ms | 103.0 ms | 103.8 ms |  7000.0000 |     - |     - |  58,600,000 B |
           Order00ManualX | 141.1 ms | 0.19 ms | 0.18 ms | 141.1 ms | 140.8 ms | 141.4 ms |  2000.0000 |     - |     - |  16,000,000 B |
```

```
BenchmarkDotNet=v0.12.1.1466-nightly, OS=Windows 10.0.17763.107 (1809/October2018Update/Redstone5)
Intel Xeon CPU E5-1650 v3 3.50GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=        2.0.3 [C:\Program Files\dotnet\sdk]
  [Host] : .NET 5.0.3 (5.0.321.7212), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable  Toolchain=InProcessEmitToolchain
IterationTime=250.0000 ms  MaxIterationCount=20  MinIterationCount=15
WarmupCount=1

                   Method |      Mean |    Error |   StdDev |    Median |       Min |       Max |      Gen 0 | Gen 1 | Gen 2 |     Allocated |
------------------------- |----------:|---------:|---------:|----------:|----------:|----------:|-----------:|------:|------:|--------------:|
        Where00LinqQueryX | 642.84 ms | 2.435 ms | 2.277 ms | 643.13 ms | 640.49 ms | 647.91 ms |  9000.0000 |     - |     - |  72,001,160 B |
       Where00LinqMethodX | 638.58 ms | 0.682 ms | 0.605 ms | 638.36 ms | 637.77 ms | 639.73 ms |  9000.0000 |     - |     - |  72,000,288 B |
              Where00ForX | 444.80 ms | 0.318 ms | 0.266 ms | 444.78 ms | 444.28 ms | 445.35 ms | 22000.0000 |     - |     - | 176,000,288 B |
        Where01LinqQueryX | 312.75 ms | 0.167 ms | 0.148 ms | 312.70 ms | 312.60 ms | 313.06 ms |  2000.0000 |     - |     - |  18,000,288 B |
       Where01LinqMethodX | 315.68 ms | 0.156 ms | 0.146 ms | 315.70 ms | 315.45 ms | 315.88 ms |  2000.0000 |     - |     - |  18,000,152 B |
 Where01LinqMethodNestedX | 383.74 ms | 0.564 ms | 0.528 ms | 383.65 ms | 382.95 ms | 384.77 ms |  7000.0000 |     - |     - |  60,000,328 B |
              Where01ForX | 262.90 ms | 0.180 ms | 0.160 ms | 262.92 ms | 262.69 ms | 263.21 ms |  2000.0000 |     - |     - |  22,000,288 B |
       Count00LinqMethodX | 880.21 ms | 0.227 ms | 0.178 ms | 880.27 ms | 879.74 ms | 880.35 ms |  5000.0000 |     - |     - |  40,000,328 B |
              Count00ForX | 361.64 ms | 0.210 ms | 0.197 ms | 361.62 ms | 361.35 ms | 362.04 ms |          - |     - |     - |         288 B |
        Order00LinqQueryX |  99.24 ms | 0.100 ms | 0.093 ms |  99.23 ms |  99.07 ms |  99.39 ms |  7000.0000 |     - |     - |  58,600,144 B |
       Order00LinqMethodX |  99.16 ms | 0.087 ms | 0.081 ms |  99.18 ms |  99.00 ms |  99.27 ms |  7250.0000 |     - |     - |  58,600,072 B |
           Order00ManualX | 139.98 ms | 0.205 ms | 0.192 ms | 139.91 ms | 139.68 ms | 140.28 ms |  2000.0000 |     - |     - |  16,000,288 B |
```

crank --config https://github.com/aspnet/Benchmarks/blob/master/scenarios/dotnet.benchmarks.yml?raw=true --scenario linq --profile aspnet-perf-win --application.framework net5.0 --application.source.repository https://github.com/adamsitnik/performance --application.source.branchOrCommit net5.0

**Comment by wfurt** [comment]
netcoreapp5.0 is long gone. can somebody please look at this @DrewScoggins and @billwert ?

**Pull request merged**
