### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Switch away from blob feeds

### CODE REVIEW

**Comment by adiaaida** [comment]
@DrewScoggins  any idea why this change would cause commandline.dragonfruit to not be found?

**Comment by mmitche** [comment]
It's probably a random package that should get pushed to another feed. I'll figure it out.

**Comment by billwert** [comment]
Do servicing branch packages for 3.1.x and 2.whatever appear in these "dotnet5" feeds you're adding?

**Comment by mmitche** [comment]
> Do servicing branch packages for 3.1.x and 2.whatever appear in these "dotnet5" feeds you're adding?

No, but I can add those separate feeds.

**Comment by DrewScoggins** [comment]
Is the dotnet-eng feed the 2.x feed?

**Comment by mmitche** [comment]
> Is the dotnet-eng feed the 2.x feed?

No, the 2.x feed is dotnet-core. However, it's only ever pushed on release day, which means the non-transport packages are on nuget.org.

**Pull request merged**
