### PR TITLE
Test System.Threading.Channels with non-default ExecutionContext

### PR DESCRIPTION
**Pull request by KorneiDontsov**
The added test shows the difference between usages of channels with and without ExecutionContext. It's good to catch ExecutionContext-related regressions in future.
Also it's used to test https://github.com/dotnet/runtime/pull/46458.

### CODE REVIEW

**Comment by KorneiDontsov** [comment]
Didn't get why some checks failed. Need help

**Comment by danmoseley** [comment]
@dotnet/area-system-threading-channels could one of you please review? I'm going through old PRs. is this a change we want?

**Comment by stephentoub** [comment]
> https://github.com/orgs/dotnet/teams/area-system-threading-channels could one of you please review? I'm going through old PRs. is this a change we want?

If we don't have perf tests around ExecutionContext capture and flow in general, or in the context of async/await, that would be fine to add.  But I don't think there's anything really specific to channels here.  It does have its own implementation of IValueTaskSource, but that's just using ExecutionContext.Capture and ExecutionContext.Run as would any IValueTaskSource.

**Comment by danmoseley** [comment]
I'm going to close this as it's not clear that it is the right way to fill that gap. Thanks.

**Pull request closed without merging**
