### PR TITLE
MauiBlazor iOS Scenarios

### PR DESCRIPTION
**Pull request by TanayParikh**
iOS version of https://github.com/dotnet/performance/pull/2386.

### CODE REVIEW

**Comment by TanayParikh** [comment]
@LoopedBard3 @DrewScoggins requesting review / merge please. (don't have perms to request GitHub review directly 😄)

**Comment by TanayParikh** [comment]
Is the `mauimaccatalyst` scenario required?

Looks like the iOS scenario is being utilized for MacCatalyst as well:

https://github.com/dotnet/runtime/blob/d5ce000205e1dff7a024035871b55a7a3bd677d8/eng/testing/performance/ios_scenarios.proj#L39

**Comment by LoopedBard3** [comment]
Ultimately, if you don't copy over the MacCatalyst helix work item there is no need to build for MacCatalyst. It is currently more of a remnant from while we were trying to get the general flow for iOS setup.

**Comment by TanayParikh** [comment]
> Ultimately, if you don't copy over the MacCatalyst helix work item there is no need to build for MacCatalyst. It is currently more of a remnant from while we were trying to get the general flow for iOS setup.

Thanks for the clarification, reverted [6a25e00](https://github.com/dotnet/performance/pull/2387/commits/6a25e009b3064a65f52bd42ef5a2cd7d19bd4e8a).

**Review by LoopedBard3 — APPROVED** [review]
LGTM

**Pull request merged**
