### PR TITLE
Add a benchmark for random.Next()

### PR DESCRIPTION
**Pull request by danmosemsft**

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by danmosemsft** [comment]
Some of the failures are just https://github.com/dotnet/runtime/pull/47923 which has a fix up but there are also failures to restore the MVC templates for 3.1:

```
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x86 with version (= 3.1.12)
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 1120 version(s) in dotnet5 [ Nearest version: 5.0.0-alpha.1.19528.5 ]
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 754 version(s) in dotnet6 [ Nearest version: 6.0.0-alpha.1.20423.5 ]
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 84 version(s) in dotnet3.1 [ Nearest version: 3.1.4-servicing.20176.4 ]
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 38 version(s) in api.nuget.org [ Nearest version: 5.0.0-preview.1.20120.5 ]
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 1 version(s) in dotnet-eng [ Nearest version: 5.0.0-alpha.1.19618.1 ]
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 0 version(s) in bdn-nightly
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 0 version(s) in dotnet-tools
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 0 version(s) in dotnet3.1-transport
[2021/02/07 22:47:37][INFO] C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj : error NU1102:   - Found 0 version(s) in dotnet5-transport
[2021/02/07 22:47:37][INFO]   Failed to restore C:\h\w\AE140943\w\AB8A095E\e\app\mvcapptemplate.csproj (in 443 ms).
```
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-performance-refs-pull-1649-merge-21e6cc946bd343bf8b/SDK%20ASP.NET%20MVC%20App%20Template%20netcoreapp3.1%20Clean%20Build/console.efd40105.log?sv=2019-07-07&se=2021-02-27T22%3A27%3A18Z&sr=c&sp=rl&sig=lJ25DBtV6IfpbQnT0MIR0t0jbUT6fEAyLR1HLjebB7E%3D

@billwert is this known?

**Comment by danmosemsft** [comment]
@wtgodbe might know?

**Comment by wtgodbe** [comment]
3.1.12 ships tomorrow, it isn't publicly available yet. How does this repo determine what 3.1 versions to restore? I don't see anything in version.props and it wasn't obvious from https://github.com/dotnet/performance/blob/09356faeb90bbfefa0a9f128b63208ad5f95735f/eng/performance/sdk_scenarios.proj, which appears to be creating the project in question

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @danmosemsft 

The CI failures are not related (scenarios and https://github.com/dotnet/runtime/issues/47856) so I am merging

**Comment by billwert** [comment]
> is this known?

as @wtgodbe says we sometimes have trouble due to the private nuget feeds. I had seen this but hadn't gotten to fixing it yet. Apologies for the noise in your PRs.

**Pull request merged**
